import test from 'node:test';
import assert from 'node:assert/strict';
import {newRun,kitchenPractice,act,card,onTable,score,value,partners,cashValue,restore,routeTargets,toolProblem} from '../game/engine.js';
import {CARDS,PACKAGES} from '../game/cards.js';
function board(kinds){const s=newRun(1);Object.assign(s,{bank:8,target:0,table:[],draw:[],discard:[],cards:[],known:[],uid:0,flips:kinds.length});for(const [zone,list]of [['table',kinds],['deck',['rice','fish','bomb']]])for(const kind of list){const c={uid:++s.uid,kind,original:kind,zone,pair:null,pairedOnce:false,tapped:false};s.cards.push(c);s[zone==='table'?'table':'draw'].push(c.uid);}return s;}
const use=(s,uid,target)=>act(s,{type:'use',uid,target});
const pair=(s,a,b,target)=>act(s,{type:'pair',ids:[a,b],target});
const residues=s=>onTable(s).filter(c=>c.kind==='residue');
function nextWith(boon){let s=board(['rice']);s=act(s,{type:'stop'});s.phase='draft';s.added=true;s.relicOffer=[];s.nextBoon=boon;s.nextRouteReward=null;return act(s,{type:'next'});}

test('Cola is cumulative 1/5/9/13/17 and cannot pair even with Wild',()=>{for(let n=1;n<=5;n++){const s=board(Array(n).fill('cola'));assert.equal(score(s),4*n-3);assert.equal(partners(s,1).length,0);}const s=board(['cola','wild']);assert.throws(()=>pair(s,1,2));assert.equal(partners(s,2).length,0);assert.ok(!routeTargets(s,'raw').some(c=>c.uid===1));});
test('Cola reprices after consumption, debt, and a card leaving the table',()=>{let s=board(['cola','cola','juicer']);assert.equal(score(s),5);s=use(s,3,1);assert.equal(value(s,card(s,2)),1);assert.equal(score(s),5);s=board(['cola','cola','debt']);assert.equal(score(s),0);card(s,3).sealedBy=99;assert.equal(score(s),5);card(s,1).sealedBy=99;assert.equal(value(s,card(s,2)),1);});
test('Fridge counts active Dried fish, including paired and temporary, but not Wild',()=>{let s=board(['fridge','fish','fish','wild']);assert.equal(value(s,card(s,1)),2);s=pair(s,2,4);assert.equal(value(s,card(s,1)),2);card(s,3).temporary=true;assert.equal(value(s,card(s,1)),2);card(s,3).sealedBy=9;assert.equal(value(s,card(s,1)),1);});
test('carry preview and cash-out account for lost set and Fridge score',()=>{for(const kinds of [['cola','cola'],['fish','fish','fridge']]){let s=board(kinds);s.relics.push('lunchbox');const expected=kinds[0]==='cola'?1:3;assert.equal(cashValue(s,1),expected);s=act(s,{type:'stop',carry:1});assert.equal(s.roundEarned,expected);assert.equal(s.bank,8+expected);}});
test('Juicer consumes one food, generates five-point Juice and a minus-one Residue without drawing',()=>{let s=board(['fish','fish','fridge','juicer']);const order=[...s.draw],flips=s.flips;assert.equal(score(s),6);s=use(s,4,1);assert.equal(card(s,1).zone,'discard');assert.equal(card(s,1).consumed,true);assert.ok(!card(s,1).paid);assert.equal(residues(s).length,1);assert.equal(value(s,residues(s)[0]),-1);assert.equal(value(s,s.cards.at(-1)),5);assert.equal(score(s),7);assert.equal(partners(s,s.cards.at(-1).uid).length,0);assert.deepEqual(s.draw,order);assert.equal(s.flips,flips);assert.deepEqual(restore(JSON.stringify(s)),s);});
test('Juicer invalid or paired targets do not spend source or create byproducts',()=>{let s=pair(board(['rice','rice','juicer']),1,2);const old=JSON.stringify(s);for(const target of [1,3,s.draw.at(-1)])assert.throws(()=>use(s,3,target));assert.equal(JSON.stringify(s),old);});
test('ordinary consumption, free costs and Boiled retention never create implicit residue',()=>{let s=board(['rice','scope']);s=act(s,{type:'use',uid:2,food:1});assert.equal(residues(s).length,0);assert.equal(card(s,1).paid,true);assert.equal(score(s),0);s=board(['rice','scope']);s.freePayments=1;s=act(s,{type:'use',uid:2});assert.equal(residues(s).length,0);s=board(['rice','scope']);card(s,1).enchantment='boiled';s=act(s,{type:'use',uid:2,food:1});assert.equal(residues(s).length,0);s=board(['rice','oil']);s=act(s,{type:'wipeOil',uid:2,food:1});assert.equal(residues(s).length,0);assert.ok(!card(s,1).paid);});
test('Composter changes existing residues to +2 without multiplying across two Composters',()=>{let s=board(['rice','juicer','composter','composter']);s=use(s,2,1);assert.equal(value(s,residues(s)[0]),2);assert.equal(score(s),7);card(s,3).sealedBy=9;assert.equal(value(s,residues(s)[0]),2);card(s,4).sealedBy=9;assert.equal(value(s,residues(s)[0]),-1);});
test('Dishwasher triggers only from actual consumption and can fund a later tool',()=>{let s=board(['rice','juicer','dishwasher','scope']);s=use(s,2,1);assert.equal(s.freePayments,1);s=use(s,4);assert.equal(s.freePayments,0);assert.equal(residues(s).length,1);s=board(['rice','scope','dishwasher']);card(s,1).enchantment='boiled';s=act(s,{type:'use',uid:2,food:1});assert.equal(s.freePayments,0);});
test('Mold costs banked points, copies base identity, and leaves source and deck intact',()=>{let s=board(['fish','mold']);card(s,1).enchantment='raw';const order=[...s.draw];s=use(s,2,1);const copy=s.cards.at(-1);assert.equal(s.bank,6);assert.equal(copy.kind,'fish');assert.ok(copy.temporary);assert.equal(copy.enchantment,undefined);assert.equal(copy.pairedOnce,false);assert.equal(card(s,1).zone,'table');assert.equal(residues(s).length,0);assert.deepEqual(s.draw,order);s=pair(s,1,copy.uid);assert.equal(score(s),8);});
test('invalid Mold use is atomic, insufficient bank disables it, and waivers cannot pay points',()=>{let s=board(['rice','mold']);const old=JSON.stringify(s);assert.throws(()=>use(s,2,s.draw.at(-1)));assert.equal(JSON.stringify(s),old);s.bank=1;s.freePayments=20;assert.equal(toolProblem(s,card(s,2)),'pointsCost');assert.throws(()=>use(s,2,1));assert.equal(s.bank,1);});
test('Popcorn creates one new unpaired card per pair; it does not pair itself recursively',()=>{let s=board(['popcorn','popcorn','wild']);s=pair(s,1,2);let token=s.cards.at(-1);assert.equal(token.kind,'popcorn');assert.equal(s.table.length,4);assert.equal(score(s),12);s=pair(s,token.uid,3);assert.equal(s.table.length,5);assert.equal(score(s),18);assert.equal(s.cards.at(-1).pair,null);assert.equal(s.log.filter(e=>e.key==='pair').length,2);assert.throws(()=>pair(s,1,2));});
test('generated-only cards never appear in deck packages or Serving-tongs discovery',()=>{for(const p of PACKAGES)assert.ok(p.cards.every(k=>!CARDS[k].tokenOnly));for(let seed=1;seed<=100;seed++){let s=board(['sorter']);s.rng=seed;s=use(s,1);assert.ok(s.pending.offers.every(k=>!CARDS[k].tokenOnly));}});
test('generated cards and residue expire; consumed permanent food resets next table',()=>{let s=use(board(['rice','juicer','composter']),2,1);s=act(s,{type:'stop'});s.phase='draft';s.added=true;s.relicOffer=[];s=act(s,{type:'next'});assert.equal(s.cards.filter(c=>c.temporary).length,0);assert.equal(card(s,1).zone,'deck');assert.equal(card(s,1).consumed,false);});
test('high die rewards are one sauce, two zero food costs, three peeks, or twelve-point Feast',()=>{let s=nextWith('sauce');assert.equal(score(s),2);assert.equal(onTable(s).filter(c=>c.kind==='wild').length,1);s=nextWith('meal');assert.equal(s.freePayments,2);s=nextWith('scout');assert.equal(s.known.length,3);s=nextWith('feast');assert.equal(score(s),12);assert.equal(onTable(s).length,4);assert.equal(onTable(s).filter(c=>c.pair).length,2);assert.equal(s.log.filter(e=>e.key==='pair').length,0);assert.throws(()=>act(s,{type:'stop'}));});
test('new-card practice demonstrates collection, consumption and copying without replacing challenge',()=>{let s=kitchenPractice();assert.equal(s.practice,true);assert.equal(score(s),15);s=use(s,6,4);assert.equal(score(s),19);assert.equal(s.freePayments,1);s=use(s,9,1);assert.equal(score(s),23);assert.equal(s.bank,6);s=pair(s,10,11);assert.equal(score(s),29);});

test('ordinary consumption still triggers Dishwasher without producing unprinted Residue',()=>{
 for(const kind of ['scope','bell','oil']){
  let s=board(['rice',kind,'dishwasher','torch']);card(s,4).tapped=true;
  s=kind==='oil'?act(s,{type:'wipeOil',uid:2,food:1}):act(s,{type:'use',uid:2,food:1,target:4});
  assert.equal(card(s,1).consumed,true,kind);assert.equal(residues(s).length,0,kind);assert.equal(s.freePayments,1,kind);
  assert.ok(!s.log.some(e=>e.key==='generate'&&e.kind==='residue'),kind);
 }
});
test('discarding food is not consuming it and cannot trigger Dishwasher or create Residue',()=>{
 let s=board(['sifter','dishwasher']);s=use(s,1);s=act(s,{type:'resolveSift',discard:true});
 assert.equal(card(s,3).zone,'discard');assert.ok(!card(s,3).consumed);assert.equal(s.freePayments,0);assert.equal(residues(s).length,0);
});
test('Juicer explicitly generates Residue once; tool fee reduction does not cancel its printed effect',()=>{
 let s=board(['rice','juicer']);s.freePayments=2;s=use(s,2,1);
 assert.equal(s.freePayments,2);assert.equal(residues(s).length,1);assert.equal(s.log.filter(e=>e.key==='generate'&&e.kind==='residue').length,1);
 assert.match(CARDS.juicer.text[0],/生成.*残渣/);assert.match(CARDS.juicer.text[1],/create.*Residue/);
 for(const k of ['scope','bell','oil'])assert.ok(CARDS[k].text.every(t=>!/残渣|Residue/.test(t)));
});
