import test from 'node:test';
import assert from 'node:assert/strict';
import {newRun,dicePractice,act,card,score,value,restore} from '../game/engine.js';
import {CARDS} from '../game/cards.js';
import {arrangeCards} from '../game/layout.js';
import {vertices,faces,orientation} from '../game/d20.js';
function fixture(table,draw=['rice','paper','bomb']){const s=newRun(31);Object.assign(s,{cards:[],uid:0,table:[],draw:[],known:[],discard:[],flips:table.length,eventCount:table.length,target:0});for(const [zone,kinds]of [['table',table],['deck',draw]])for(const kind of kinds){const c={uid:++s.uid,original:kind,kind,zone,tapped:false,pair:null,pairedOnce:false,sealedBy:null,ferment:null,caught:null,paid:false,triggers:0,freeCost:false,multiplier:1};s.cards.push(c);s[zone==='table'?'table':'draw'].push(c.uid);}return s;}
const draw=s=>act(s,{type:'draw'});
function rolled(value){for(let seed=0;seed<1000;seed++){const s=dicePractice();s.rng=seed;const r=act(s,{type:'roll'});if(r.dice.result.total===value)return r;}throw Error('outcome unreachable');}
test('small scoring is exactly 1, 2+2, and tea doubles only its next food',()=>{let s=fixture(['tea','wild'],['rice','rice','bomb']);assert.equal(score(s),2);s=act(s,{type:'pair',ids:[1,2]});assert.equal(score(s),4);s=draw(s);assert.equal(value(s,card(s,3)),2);s=draw(s);assert.equal(value(s,card(s,4)),1);s=act(s,{type:'pair',ids:[3,4]});assert.equal(value(s,card(s,3)),4);assert.equal(value(s,card(s,4)),2);assert.equal(score(s),10);});
test('tea next-card promise expires on a non-food; peeking does not consume it',()=>{let s=fixture(['tea','wild','torch'],['paper','rice','bomb']);s=act(s,{type:'pair',ids:[1,2]});s=act(s,{type:'use',uid:3});assert.equal(s.nextEffects.length,1);s=draw(draw(s));assert.equal(value(s,card(s,5)),1);assert.equal(s.nextEffects.length,0);});
test('ginger clears only the immediately next trouble, with no bundled peek',()=>{let s=fixture(['ginger','wild'],['paper','debt','bomb']);s=act(s,{type:'pair',ids:[1,2]});assert.equal(s.known.length,0);s=draw(s);assert.equal(card(s,3).zone,'discard');s=draw(s);assert.equal(card(s,4).zone,'table');});
test('toast only reclaims spent food; its reveal does not ready tools',()=>{let s=fixture(['toast','wild','rice','scope'],['toast','bomb']);s=act(s,{type:'use',uid:4,food:3});s=draw(s);assert.equal(card(s,4).tapped,true);s=act(s,{type:'pair',ids:[1,2],target:3});assert.equal(card(s,3).zone,'table');assert.equal(s.flips,5);});
test('each prediction watches one reveal, then expires even on mismatch',()=>{for(const [kind,hit]of [['wish','rice'],['candle','paper'],['timetable','torch']]){let s=fixture([kind],[hit,'rice','bomb']);s=draw(s);assert.equal(s.known.length,1);assert.equal(card(s,1).triggers,1);s=fixture([kind],['mint','paper','bomb']);if(kind==='wish')s=fixture([kind],['torch','rice','bomb']);s=draw(draw(s));assert.equal(s.known.length,0);}});
test('preheater transforms next food without a second reveal event',()=>{let s=fixture(['stove'],['rice','fish','bomb']);s=draw(s);assert.equal(card(s,2).kind,'wild');assert.equal(s.flips,2);s=draw(s);assert.equal(card(s,3).kind,'fish');});
test('relay grants one local waiver and rust exhausts only an immediate tool',()=>{let s=fixture(['relay','rust'],['scope','cloth','bomb']);s=draw(s);assert.equal(card(s,3).freeCost,true);assert.equal(card(s,3).tapped,true);s=draw(s);assert.equal(card(s,4).freeCost,false);assert.equal(card(s,4).tapped,false);});
test('sieve filters trouble without peeking, revealing, or moving any remaining identity',()=>{let s=fixture(['sifter','rice','noise'],['paper','bomb','rice']);s=act(s,{type:'use',uid:1,food:2});assert.deepEqual(s.draw,[5,6]);assert.equal(s.known.length,0);assert.equal(s.delayedPeeks.length,0);assert.equal(s.flips,3);s=fixture(['sifter','rice'],['bomb','paper']);s=act(s,{type:'use',uid:1,food:2});assert.equal(s.draw[0],3);assert.equal(s.phase,'play');});
test('noise delays once, and bomb beats all next-card and delayed effects',()=>{let s=fixture(['noise','torch','stove'],['rice','bomb']);s=act(s,{type:'use',uid:2});s=draw(s);assert.deepEqual(s.known,[5]);assert.equal(s.delayedPeeks.length,0);s=fixture(['noise','torch','stove'],['bomb','rice']);s=act(s,{type:'use',uid:2});s=draw(s);assert.equal(s.reason,'bomb');assert.equal(s.delayedPeeks.length,1);assert.equal(card(s,3).triggers,0);});
test('free tool costs are atomic and local waiver precedes meal tickets',()=>{let s=fixture(['scope','cloth','paper']);s.freePayments=2;card(s,1).freeCost=true;s=act(s,{type:'use',uid:1});assert.equal(s.freePayments,2);assert.equal(card(s,1).freeCost,false);const old=JSON.stringify(s);assert.throws(()=>act(s,{type:'use',uid:2,target:999}));assert.equal(JSON.stringify(s),old);s=act(s,{type:'use',uid:2,target:3});assert.equal(s.freePayments,1);});
test('d20 has all 20 outcomes, correct bands, and an approximately uniform fixed-seed sample',()=>{const counts=Array(20).fill(0);for(let seed=0;seed<6000;seed++){let s=dicePractice();s.rng=seed;s=act(s,{type:'roll'});const d=s.dice.result;assert.ok(Number.isInteger(d.total)&&d.total>=1&&d.total<=20);counts[d.total-1]++;assert.equal(d.locked,d.total===1||d.total===20);assert.equal(d.tier,d.total===1?'criticalLow':d.total===20?'criticalHigh':d.total<=5?'low':d.total>=15?'high':'steady');}assert.ok(counts.every(n=>n>230&&n<370),counts.join(','));});
test('natural 1 and 20 cannot reroll, including after save/reload',()=>{for(const n of [1,20]){const s=restore(JSON.stringify(rolled(n)));assert.throws(()=>act(s,{type:'roll'}),/rollLimit/);}let s=rolled(7);s=act(s,{type:'roll'});assert.equal(s.dice.rolls.length,2);assert.throws(()=>act(s,{type:'roll'}),/rollLimit/);});
test('every accepted die adds its exact value once; only accepted rewards commit',()=>{for(let n=1;n<=20;n++){const s=rolled(n),r=act(s,{type:'acceptDice',boon:'sauce'});assert.equal(r.target,3+n);assert.equal(r.bank,4);assert.equal(r.cards.length,20+(n===1?3:n<=5?1:0));assert.equal(r.nextBoon,n===20?'feast':n>=15?'sauce':null);assert.throws(()=>act(r,{type:'acceptDice',boon:'sauce'}));}assert.throws(()=>act(dicePractice(),{type:'acceptDice'}));});
test('natural 20 grants exactly three temporary pairs worth 12, without pair triggers',()=>{let s=act(act(rolled(20),{type:'acceptDice'}),{type:'next'});assert.equal(score(s),12);assert.equal(s.cards.filter(c=>c.temporary).length,6);assert.equal(s.flips,0);assert.equal(s.log.filter(e=>e.key==='pair').length,0);assert.equal(s.draw.length,20);s.flips=1;s.target=0;s=act(s,{type:'stop'});s=act(act(s,{type:'roll'}),{type:'acceptDice',boon:'sauce'});assert.ok(!s.cards.some(c=>c.temporary));});
test('natural 1 grants distinct troubles and each transition still has one free removal',()=>{let s=act(rolled(1),{type:'acceptDice'});for(const k of ['debt','rust','paper'])assert.ok(s.cards.some(c=>c.original===k));s=act(s,{type:'remove',uid:s.cards.find(c=>c.original==='debt').uid});assert.throws(()=>act(s,{type:'remove',uid:s.cards.find(c=>c.original==='rust').uid}));});
test('high roll sauce is two temporary cards and cannot be carried permanently',()=>{let s=act(act(rolled(18),{type:'acceptDice',boon:'sauce'}),{type:'next'});assert.equal(s.cards.filter(c=>c.temporary).length,2);assert.equal(score(s),2);s.relics.push('lunchbox');s.flips=1;assert.throws(()=>act(s,{type:'stop',carry:s.cards.find(c=>c.temporary).uid}));});
test('card definitions use one effect sentence in both languages',()=>{for(const c of Object.values(CARDS))for(const text of c.text){assert.ok((text.match(/[。.!?]/g)||[]).length<=1,c.name+': '+text);}assert.equal(Object.keys(CARDS).length,27);});
test('d20 mesh is a closed icosahedron with opposite labels summing to 21',()=>{assert.equal(vertices.length,12);assert.equal(faces.length,20);const edges=new Map();for(const f of faces){for(let i=0;i<3;i++){const key=[f.ids[i],f.ids[(i+1)%3]].sort((a,b)=>a-b).join(',');edges.set(key,(edges.get(key)||0)+1);}const o=faces.find(g=>f.normal.reduce((n,x,i)=>n+x*g.normal[i],0)<-.999);assert.equal(f.value+o.value,21);const m=orientation(f.value);assert.ok(Math.abs(m[2].reduce((n,x,i)=>n+x*f.normal[i],0)-1)<1e-8);}assert.equal(edges.size,30);assert.ok([...edges.values()].every(n=>n===2));});
test('table shrink precedes pagination; every card stays in at most four rows per page',()=>{for(const [w,h]of [[1080,350],[1580,520],[360,240]])for(const n of [0,5,16,30,80,200]){const cards=Array.from({length:n},(_,i)=>({uid:i+1,tapped:i%4===0}));const l=arrangeCards(cards,w,h);assert.deepEqual(l.pages.flat(2),cards.map(c=>c.uid));assert.ok(l.pages.every(rows=>rows.length<=4));assert.ok(l.rowH*l.pages[0].length<=h+1);if(l.pages.length>1)assert.equal(l.pages[0].length,4);}const a=arrangeCards(Array.from({length:10},(_,i)=>({uid:i})),1000,400),b=arrangeCards(Array.from({length:35},(_,i)=>({uid:i})),1000,400);assert.ok(b.scale<a.scale);assert.equal(b.pages.length,1);});
