import {dicePractice} from './fixtures.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {newRun,act,card,score,restore,routeTargets} from '../game/engine.js';
import {CARDS,PACKAGES,typeOf} from '../game/cards.js';
import {ENCHANTMENTS,ROUTES} from '../game/routes.js';
function board(kinds){const s=newRun(97);Object.assign(s,{cards:[],draw:[],table:[],discard:[],known:[],uid:0,target:0,flips:kinds.length});for(const [zone,list] of [['table',kinds],['deck',['rice','fish','bomb']]])for(const kind of list){const c={uid:++s.uid,original:kind,kind,zone,pair:null,pairedOnce:false,tapped:false};s.cards.push(c);s[zone==='table'?'table':'draw'].push(c.uid);}return s;}
const pair=(s,a,b,target)=>act(s,{type:'pair',ids:[a,b],target});
function paths(round=1){let s=dicePractice();s.practice=false;s.round=round;s.bank=25;return act(act(s,{type:'roll'}),{type:'acceptDice',boon:'meal'});}
function chosen(id,uid){const s=paths();s.routeOffers=[id,id==='tea'?'raw':'tea'];return act(s,{type:'chooseRoute',id,uid});}
function next(s){s=act(s,{type:'add',id:s.offers[0]});if(s.relicOffer.length)s=act(s,{type:'chooseRelic',id:s.relicOffer[0]});return act(s,{type:'next'});}

test('nine round-end choices are two distinct persisted paths; removal appears occasionally',()=>{for(let round=1;round<10;round++){const s=paths(round);assert.equal(s.phase,'route');assert.equal(new Set(s.routeOffers).size,2);assert.equal(s.routeOffers.includes('prune'),[2,5,8].includes(round));assert.deepEqual(restore(JSON.stringify(s)),s);assert.throws(()=>act(s,{type:'next'}));assert.throws(()=>act(s,{type:'add',id:'sorter'}));}});
test('each package includes trouble and taking exactly one is mandatory',()=>{for(const p of PACKAGES)assert.ok(p.cards.some(k=>CARDS[k].type==='trouble'),p.id);let s=chosen('tea');assert.throws(()=>act(s,{type:'next'}),/choosePackage/);s=act(s,{type:'add',id:s.offers[0]});assert.throws(()=>act(s,{type:'add',id:s.offers[0]}));assert.equal(act(s,{type:'next'}).round,2);});
test('enchantment targets permanent original food only; cannot overwrite, enchant tools or bomb',()=>{const s=paths();s.routeOffers=['raw','tea'];card(s,1).enchantment='fried';card(s,2).kind='wild';const temp={...card(s,3),uid:++s.uid,temporary:true};s.cards.push(temp);s.table.push(temp.uid);temp.zone='table';assert.ok(routeTargets(s,'raw').some(c=>c.uid===2));for(const uid of [1,temp.uid,s.cards.find(c=>typeOf(c)==='tool').uid,20])assert.throws(()=>act(s,{type:'chooseRoute',id:'raw',uid}));const r=act(s,{type:'chooseRoute',id:'raw',uid:2});assert.equal(card(r,2).enchantment,'raw');assert.equal(card(s,2).enchantment,undefined);assert.throws(()=>act(r,{type:'chooseRoute',id:'tea'}));});
test('enchantments survive draft, shuffle, next table and reload; usage refreshes',()=>{for(const id of Object.keys(ENCHANTMENTS)){let s=chosen(id,1);card(s,1).boiledUsed=true;card(s,1).kind='wild';s=next(s);assert.equal(card(s,1).enchantment,id);assert.equal(card(s,1).kind,'rice');assert.equal(card(s,1).boiledUsed,false);assert.deepEqual(restore(JSON.stringify(s)),s);assert.equal(s.routeHistory.length,1);assert.equal(card(s,s.draw[0]).kind==='bomb',false);}});
test('raw food has 4 unpaired points, still 4 when paired; debt and sealing take precedence',()=>{let s=board(['rice','rice','debt']);card(s,1).enchantment='raw';assert.equal(score(s),0);s=pair(s,1,2,3);assert.equal(score(s),8);s=board(['rice','fish']);card(s,1).enchantment='raw';assert.equal(score(s),6);card(s,1).sealedBy=99;assert.equal(score(s),2);});
test('fried stacks per enchanted card with tea and relay, without re-pair exploitation',()=>{let s=board(['tea','tea','relay']);card(s,1).enchantment='fried';card(s,2).enchantment='fried';s=pair(s,1,2);assert.equal(s.freePayments,5);assert.equal(score(s),8);assert.throws(()=>pair(s,1,2));});
test('boiled keeps first paid food, second payment discards it; invalid use is atomic',()=>{let s=board(['rice','scope','bell']);card(s,1).enchantment='boiled';const original=JSON.stringify(s);assert.throws(()=>act(s,{type:'use',uid:3,food:1,target:99}));assert.equal(JSON.stringify(s),original);s=act(s,{type:'use',uid:2,food:1});assert.equal(card(s,1).zone,'table');assert.equal(card(s,1).boiledUsed,true);assert.ok(!card(s,1).paid);s=act(s,{type:'use',uid:3,food:1,target:2});assert.equal(card(s,1).zone,'discard');assert.equal(card(s,1).paid,true);});
test('boiled protection remains spent after reclaim; free waivers and oil wiping do not trigger it',()=>{let s=board(['rice','scope','bell','toast','toast']);card(s,1).enchantment='boiled';s=act(s,{type:'use',uid:2,food:1});s=act(s,{type:'use',uid:3,food:1,target:2});s=pair(s,4,5,1);s=act(s,{type:'use',uid:2,food:1});assert.equal(card(s,1).zone,'discard');s=board(['rice','scope']);card(s,1).enchantment='boiled';s.freePayments=1;s=act(s,{type:'use',uid:2});assert.ok(!card(s,1).boiledUsed);s=board(['rice','oil']);card(s,1).enchantment='boiled';s=act(s,{type:'wipeOil',uid:2,food:1});assert.equal(card(s,1).zone,'discard');assert.ok(!card(s,1).boiledUsed);});
test('boiled paired payment via timetable leaves pair and points intact',()=>{let s=board(['rice','rice','timetable','scope']);card(s,1).enchantment='boiled';s=pair(s,1,2);s=act(s,{type:'use',uid:4,food:1});assert.equal(score(s),8);assert.ok(card(s,1).pair===card(s,2).pair&&card(s,1).pair);});
test('route bonuses stack with die boons and expire after one start',()=>{let s=chosen('tea');s.nextBoon='meal';s=next(s);assert.equal(s.freePayments,4);assert.equal(s.nextRouteReward,null);s=chosen('helper');s.nextBoon='feast';s=next(s);assert.equal(score(s),12);assert.equal(s.cards.filter(c=>c.temporary).length,5);const torch=s.cards.find(c=>c.temporary&&c.kind==='torch');assert.ok(!s.draw.includes(torch.uid));assert.equal(s.flips,0);s=act(s,{type:'use',uid:torch.uid});assert.equal(s.known.length,1);s=next(chosen('lantern'));assert.equal(s.known.length,3);});
test('paid removal deducts bank not target, clears carry and all zones, cannot remove bomb',()=>{let s=paths(2);s.routeOffers=['prune','tea'];s.carry=1;s.known=[1];const bank=s.bank,target=s.target,original=JSON.stringify(s);assert.throws(()=>act(s,{type:'chooseRoute',id:'prune',uid:20}));assert.equal(JSON.stringify(s),original);s=act(s,{type:'chooseRoute',id:'prune',uid:1});assert.equal(s.bank,bank-4);assert.equal(s.target,target);assert.equal(s.carry,null);assert.ok(!card(s,1));assert.ok(['draw','table','discard','known'].every(z=>!s[z].includes(1)));assert.equal(s.phase,'draft');assert.throws(()=>act(s,{type:'chooseRoute',id:'prune',uid:2}));});
test('unaffordable or unoffered route cannot charge points; offer generation omits it',()=>{let s=paths();s.routeOffers=['prune','tea'];s.bank=3;const before=JSON.stringify(s);assert.throws(()=>act(s,{type:'chooseRoute',id:'prune',uid:1}),/routeCost/);assert.throws(()=>act(s,{type:'chooseRoute',id:'lantern'}));assert.equal(JSON.stringify(s),before);s=dicePractice();s.round=2;s.bank=3;s=act(act(s,{type:'roll'}),{type:'acceptDice',boon:'meal'});assert.ok(!s.routeOffers.includes('prune'));});
test('discover resumes identical choices after reload and grants only the selected food',()=>{let s=board(['sorter']);const order=[...s.draw],count=s.cards.length;s=act(s,{type:'use',uid:1});const saved=JSON.stringify(s);assert.deepEqual(restore(saved),s);assert.throws(()=>act(s,{type:'discover',kind:'bomb'}));assert.throws(()=>act(s,{type:'draw'}));assert.throws(()=>act(s,{type:'stop'}));assert.equal(JSON.stringify(s),saved);const kind=s.pending.offers[1];s=act(restore(saved),{type:'discover',kind});assert.equal(s.cards.length,count+1);assert.equal(s.cards.at(-1).kind,kind);assert.ok(s.cards.at(-1).temporary);assert.equal(s.pending,null);assert.deepEqual(s.draw,order);assert.equal(s.flips,1);assert.throws(()=>act(s,{type:'discover',kind}));});
test('discovered food can pair but cannot be carried, permanently enchanted or remain next round',()=>{let s=board(['sorter']);s=act(s,{type:'use',uid:1});const kind=s.pending.offers.find(k=>k!=='wild'&&!CARDS[k].noPair&&k!=='popcorn');s=act(s,{type:'discover',kind});const token=s.cards.at(-1);card(s,2).kind=card(s,2).original=kind;s=act(s,{type:'draw'});s=pair(s,token.uid,2);assert.equal(score(s),8);s.relics.push('lunchbox');assert.throws(()=>act(s,{type:'stop',carry:token.uid}));s=act(s,{type:'stop'});s=act(act(s,{type:'roll'}),{type:'acceptDice',boon:'meal'});assert.ok(!routeTargets(s,'raw').some(c=>c.uid===token.uid));s.routeOffers=['tea','raw'];s=act(s,{type:'chooseRoute',id:'tea'});assert.ok(!card(s,token.uid));});
test('malformed route, enchantment or discovery saves are rejected',()=>{let s=paths();s.routeOffers=['tea','tea'];assert.equal(restore(JSON.stringify(s)),null);s=newRun();card(s,20).enchantment='raw';assert.equal(restore(JSON.stringify(s)),null);s=act(board(['sorter']),{type:'use',uid:1});s.pending.offers=['rice','rice','bomb'];assert.equal(restore(JSON.stringify(s)),null);});
