import {practiceRun,dicePractice} from './fixtures.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {newRun,act,card,onTable,score,value,partners,payableFoods,restore,toolProblem,INITIAL_TARGET} from '../game/engine.js';
import {CARDS,typeOf} from '../game/cards.js';
import {vertices,faces,orientation} from '../game/d20.js';
import {arrangeCards} from '../game/layout.js';
function fixture(table,deck=['paper','bomb']){
 const s=newRun(124);Object.assign(s,{cards:[],uid:0,table:[],draw:[],discard:[],known:[],flips:table.length,target:0});
 for(const [zone,kinds] of [['table',table],['deck',deck]])for(const kind of kinds){const c={uid:++s.uid,original:kind,kind,zone,tapped:false,pair:null,pairedOnce:false,sealedBy:null,ferment:null,paid:false,entered:s.uid,triggers:0,freeCost:false};s.cards.push(c);s[zone==='table'?'table':'draw'].push(c.uid);}return s;
}
const draw=s=>act(s,{type:'draw'}),pair=(s,a,b,target)=>act(s,{type:'pair',ids:[a,b],target});
function rolled(n){for(let seed=0;seed<1000;seed++){let s=dicePractice();s.rng=seed;s=act(s,{type:'roll'});if(s.dice.result.total===n)return s;}throw Error('unreachable die');}
function route(s){return act(s,{type:'chooseRoute',id:s.routeOffers.find(id=>['lantern','tea','helper'].includes(id))||s.routeOffers[0],...(!s.routeOffers.some(id=>['lantern','tea','helper'].includes(id))?{uid:s.cards.find(c=>CARDS[c.original].type==='food'&&!c.enchantment&&!c.temporary).uid}:{})});}
function draft(s){return route(act(act(s,{type:'roll'}),{type:'acceptDice',boon:'scout'}));}
function next(s){s=act(s,{type:'add',id:s.offers[0]});if(s.relicOffer.length)s=act(s,{type:'chooseRelic',id:s.relicOffer[0]});return act(s,{type:'next'});}

test('default is 14 foods, four tools, one device and one bomb in 20 cards',()=>{const s=newRun(9),counts={};for(const c of s.cards)counts[typeOf(c)]=(counts[typeOf(c)]||0)+1;assert.deepEqual(counts,{food:14,tool:4,device:1,bomb:1});});
test('first reveal safe; second bomb still possible without hidden score protection',()=>{let bombs=0;for(let seed=1;seed<=600;seed++){const s=newRun(seed);assert.notEqual(card(s,s.draw[0]).kind,'bomb');if(card(s,s.draw[1]).kind==='bomb')bombs++;}assert.ok(bombs>10&&bombs<70);});
test('single food is 2 and a pair is exactly 4+4',()=>{let s=fixture(['rice','rice','fish']);assert.equal(score(s),6);s=pair(s,1,2);assert.equal(value(s,card(s,1)),4);assert.equal(value(s,card(s,2)),4);assert.equal(score(s),10);});
test('a third matching food never triples or reuses a pair',()=>{let s=pair(fixture(['fish','fish','fish','wild']),1,2);assert.equal(score(s),12);assert.throws(()=>pair(s,1,3));s=pair(s,3,4);assert.equal(score(s),16);assert.equal(s.log.filter(e=>e.key==='pair').length,2);});
test('wild cannot pair with wild; cling film prevents wild pairing until cleared',()=>{let s=fixture(['wild','wild','rice','wrap','cloth']);assert.equal(partners(s,1).length,0);assert.throws(()=>pair(s,1,3));s=act(s,{type:'use',uid:5,target:4});assert.deepEqual(partners(s,1).map(c=>c.uid),[3]);s=pair(s,1,3);assert.equal(score(s),10);});
test('rice clears trouble and scores even if no target exists',()=>{let s=pair(fixture(['rice','rice','debt']),1,2,3);assert.equal(card(s,3).zone,'discard');assert.equal(score(s),8);assert.equal(score(pair(fixture(['rice','rice']),1,2)),8);});
test('fish and candle reveal known identities, never trigger or move bomb',()=>{let s=fixture(['fish','fish','candle'],['bomb','rice']);const order=[...s.draw];s=pair(s,1,2);assert.equal(s.phase,'play');assert.deepEqual(s.draw,order);assert.deepEqual(s.known,order);assert.equal(s.flips,3);});
test('candlestick repeats on different pairs with no next-card expiry',()=>{let s=fixture(['rice','rice','candle'],['mint','mint','fish','paper','bomb']);s=pair(s,1,2);assert.deepEqual(s.known,[4,5]);s=draw(draw(s));s=pair(s,4,5);assert.deepEqual(s.known,[6,7]);assert.equal(s.log.filter(e=>e.key==='peek').length,2);});
test('relay grants cumulative waivers on each pair, even across reveals',()=>{let s=fixture(['relay','rice','rice','tea','tea']);s=pair(s,2,3);assert.equal(s.freePayments,1);s=draw(s);s=pair(s,4,5);assert.equal(s.freePayments,4);});
test('tea grants two waivers which free tools do not consume',()=>{let s=pair(fixture(['tea','tea','torch','scope','bell']),1,2);s=act(s,{type:'use',uid:3});assert.equal(s.freePayments,2);s=act(s,{type:'use',uid:4});assert.equal(s.freePayments,1);s=act(s,{type:'use',uid:5,target:3});assert.equal(s.freePayments,0);assert.equal(card(s,3).tapped,false);assert.equal(score(s),8);});
test('invalid paid tool target leaves food, tickets and tap state untouched',()=>{let s=fixture(['bell','rice','torch']);card(s,3).tapped=true;const before=JSON.stringify(s);assert.throws(()=>act(s,{type:'use',uid:1,food:2,target:1}));assert.equal(JSON.stringify(s),before);s.freePayments=1;const free=JSON.stringify(s);assert.throws(()=>act(s,{type:'use',uid:1,target:999}));assert.equal(JSON.stringify(s),free);});
test('mint can ready a used tool and each repeat use still pays its cost',()=>{let s=fixture(['mint','mint','scope','rice','fish']);s=act(s,{type:'use',uid:3,food:4});s=pair(s,1,2,3);assert.equal(card(s,3).tapped,false);s=act(s,{type:'use',uid:3,food:5});assert.equal(card(s,4).zone,'discard');assert.equal(card(s,5).zone,'discard');});
test('ginger refreshes used relics but cannot refresh by re-pairing itself',()=>{let s=fixture(['ginger','wild']);s=act(s,{type:'relic',id:'shaker'});assert.throws(()=>act(s,{type:'relic',id:'shaker'}));s=pair(s,1,2);assert.equal(s.relicUsed.shaker,undefined);s=act(s,{type:'relic',id:'shaker'});assert.equal(s.relicUsed.shaker,true);assert.throws(()=>pair(s,1,2));});
test('toast takes back one spent food without creating a reveal',()=>{let s=fixture(['toast','wild','rice','scope']);s=act(s,{type:'use',uid:4,food:3});s=pair(s,1,2,3);assert.equal(card(s,3).zone,'table');assert.equal(card(s,3).paid,false);assert.equal(s.flips,4);assert.equal(score(s),10);});
test('timetable makes paired food a payable choice; payment breaks pair without resetting history',()=>{let s=pair(fixture(['rice','rice','scope','timetable','toast','wild']),1,2);assert.ok(payableFoods(s).some(c=>c.uid===1));s=act(s,{type:'use',uid:3,food:1});assert.equal(card(s,2).pair,null);assert.equal(value(s,card(s,2)),2);s=pair(s,5,6,1);assert.equal(card(s,1).zone,'table');assert.equal(partners(s,1).length,0);assert.equal(score(s),12);});
test('without timetable paired food cannot pay and malformed payment remains atomic',()=>{let s=pair(fixture(['rice','rice','scope']),1,2);const snapshot=JSON.stringify(s);assert.equal(toolProblem(s,card(s,3)),'foodCost');assert.throws(()=>act(s,{type:'use',uid:3,food:1}));assert.equal(JSON.stringify(s),snapshot);});
test('sauce stove transforms a chosen food immediately without reset or hidden draw',()=>{let s=fixture(['stove','rice','fish']);const order=[...s.draw];s=act(s,{type:'use',uid:1,target:2});assert.equal(card(s,2).kind,'wild');assert.equal(card(s,2).original,'rice');assert.equal(s.flips,3);assert.deepEqual(s.draw,order);s=pair(s,2,3);assert.equal(score(s),8);});
test('jar immediately converts an active trouble; cannot target a food or bomb',()=>{let s=fixture(['jar','noise','fish']);assert.throws(()=>act(s,{type:'use',uid:1,target:3}));s=act(s,{type:'use',uid:1,target:2});assert.equal(card(s,2).kind,'wild');assert.equal(s.flips,3);s=pair(s,2,3);assert.equal(s.known.length,1);});
test('wish creates exactly one temporary sauce without a second reveal event',()=>{let s=fixture([],['wish','rust','bomb']);s=draw(s);assert.equal(s.flips,1);assert.equal(s.table.length,2);assert.equal(s.draw.length,2);const token=onTable(s).find(c=>c.temporary);assert.equal(token.kind,'wild');assert.equal(score(s),2);assert.deepEqual(s.lastReveal,{uid:1,kind:'wish',type:'device',number:1});});
test('temporary wish token cannot be carried and never becomes a permanent deck card',()=>{let s=draw(fixture([],['wish','rice','bomb']));s.relics.push('lunchbox');assert.throws(()=>act(s,{type:'stop',carry:s.table[1]}));s=act(s,{type:'stop'});s=draft(s);assert.equal(s.cards.length,3);assert.ok(!s.cards.some(c=>c.temporary));});
test('sieve reveals unknown top, then optionally discards without consuming a reveal',()=>{let s=fixture(['sifter'],['paper','bomb','fish']);s=act(s,{type:'use',uid:1});assert.deepEqual(s.known,[2]);assert.deepEqual(s.draw,[2,3,4]);assert.equal(s.flips,1);assert.equal(s.pending.type,'sift');assert.equal(card(s,1).tapped,true);assert.throws(()=>draw(s));s=act(s,{type:'resolveSift',discard:true});assert.deepEqual(s.draw,[3,4]);assert.equal(card(s,2).zone,'discard');assert.equal(s.pending,null);assert.equal(s.flips,1);});
test('sieve can keep useful food and preserves pending choice across reload',()=>{let s=fixture(['sifter'],['fish','bomb']);s=act(s,{type:'use',uid:1});const r=restore(JSON.stringify(s));assert.deepEqual(s,r);s=act(r,{type:'resolveSift',discard:false});assert.deepEqual(s.draw,[2,3]);assert.deepEqual(s.known,[2]);assert.equal(s.pending,null);assert.throws(()=>act(s,{type:'resolveSift',discard:true}));});
test('sieve safely inspects bomb but rejects discarding it atomically',()=>{let s=act(fixture(['sifter'],['bomb','fish']),{type:'use',uid:1});assert.equal(s.phase,'play');const before=JSON.stringify(s);assert.throws(()=>act(s,{type:'resolveSift',discard:true}));assert.equal(JSON.stringify(s),before);s=act(s,{type:'resolveSift',discard:false});assert.equal(draw(s).reason,'bomb');});
test('interference prevents sieve from peeking unknown cards, not using existing information',()=>{let s=fixture(['sifter','noise'],['fish','bomb']);assert.equal(toolProblem(s,card(s,1)),'noPeek');assert.throws(()=>act(s,{type:'use',uid:1}));s.known=[3];s=act(s,{type:'use',uid:1});s=act(s,{type:'resolveSift',discard:true});assert.deepEqual(s.draw,[4]);});
test('serving tongs discover a temporary food outside the deck without moving the bomb',()=>{let s=fixture(['sorter'],['fish','paper','bomb']);const order=[...s.draw];s=act(s,{type:'use',uid:1});assert.equal(s.pending.type,'discover');assert.equal(s.pending.offers.length,3);assert.equal(new Set(s.pending.offers).size,3);assert.throws(()=>draw(s));s=act(s,{type:'discover',kind:s.pending.offers[0]});assert.equal(s.cards.length,5);assert.ok(s.cards.at(-1).temporary);assert.equal(s.flips,1);assert.deepEqual(s.draw,order);});
test('interference blocks peeks instead of delaying them; clearing restores future peeks',()=>{let s=fixture(['torch','noise','cloth','scope','rice']);s.known=[6];s=act(s,{type:'use',uid:1});assert.deepEqual(s.known,[6]);assert.equal(s.delayedPeeks.length,0);s=act(s,{type:'use',uid:3,target:2});s=act(s,{type:'use',uid:4,food:5});assert.deepEqual(s.known,[6,7]);});
test('fog limits each peek but retains existing knowledge',()=>{let s=fixture(['scope','rice','fog'],['fish','mint','bomb']);s.known=[5];s=act(s,{type:'use',uid:1,food:2});assert.deepEqual(s.known,[5,4]);});
test('rust affects all new tools until cleared, not tools already on the table',()=>{let s=fixture(['rust','torch','cloth'],['scope','stove','bomb']);s=draw(draw(s));assert.equal(card(s,2).tapped,false);assert.equal(card(s,4).tapped,true);assert.equal(card(s,5).tapped,true);s=act(s,{type:'use',uid:3,target:1});assert.equal(card(s,4).tapped,true);});
test('oil disables tools; wiping pays food but toast cannot reclaim that payment',()=>{let s=fixture(['oil','rice','torch']);assert.throws(()=>act(s,{type:'use',uid:3}));s=act(s,{type:'wipeOil',uid:1,food:2});assert.equal(card(s,2).paid,false);s=act(s,{type:'use',uid:3});assert.equal(s.known.length,1);});
test('debt removes only unpaired score, not food payment access',()=>{let s=fixture(['debt','rice','rice','scope']);assert.equal(score(s),0);s=pair(s,2,3);assert.equal(score(s),8);let t=fixture(['debt','rice','scope']);t=act(t,{type:'use',uid:3,food:2});assert.equal(card(t,2).zone,'discard');});
test('shuffle preserves remaining identities and can put bomb on top after first reveal',()=>{let found=false;for(let seed=1;seed<80;seed++){let s=fixture(['rice'],['fish','paper','bomb']);s.rng=seed;s.known=[...s.draw];const ids=[...s.draw].sort();s=act(s,{type:'relic',id:'shaker'});assert.deepEqual([...s.draw].sort(),ids);assert.equal(s.known.length,0);if(card(s,s.draw[0]).kind==='bomb')found=true;assert.throws(()=>act(s,{type:'relic',id:'shaker'}));}assert.ok(found);});
test('revealed bomb terminates immediately and later relic actions are rejected',()=>{let s=fixture(['candle','relay'],['bomb','wish']);s=draw(s);assert.equal(s.reason,'bomb');assert.equal(s.table.length,3);assert.equal(s.known.length,0);assert.equal(s.freePayments,0);assert.throws(()=>act(s,{type:'relic',id:'shaker'}));});
test('practice supports transform, pair, ready and peek without sacrificing food',()=>{let s=practiceRun();s=act(s,{type:'use',uid:3,target:4});s=pair(s,1,4,2);s=act(s,{type:'use',uid:2});assert.equal(score(s),8);assert.equal(card(s,s.known[0]).kind,'paper');assert.equal(s.flips,4);});
test('carry forgoes exactly 2 points and does not consume first reveal protection',()=>{let s=fixture(['rice','fish'],['mint','bomb']);s.relics.push('lunchbox');s=act(s,{type:'stop',carry:1});assert.equal(s.roundEarned,2);s=next(draft(s));assert.deepEqual(s.table,[1]);assert.equal(s.flips,0);assert.notEqual(card(s,s.draw[0]).kind,'bomb');});
test('draft requires one addition, has no free removal, and resets transformations',()=>{let s=fixture(['stove','rice'],['fish','bomb']);s=act(s,{type:'use',uid:1,target:2});s=act(s,{type:'stop'});s=draft(s);assert.throws(()=>act(s,{type:'next'}),/choosePackage/);const old=JSON.stringify(s);assert.throws(()=>act(s,{type:'remove',uid:4}));assert.throws(()=>act(s,{type:'remove',uid:3}));assert.equal(JSON.stringify(s),old);s=act(s,{type:'add',id:s.offers[0]});assert.throws(()=>act(s,{type:'add',id:s.offers[1]}));s=act(s,{type:'next'});assert.equal(card(s,2).kind,'rice');assert.equal(card(s,1).tapped,false);assert.ok(card(s,3));});
test('cash out wins on table ten, while table five continues to the next stakes',()=>{let s=pair(fixture(['fish','fish']),1,2);s.round=10;s.bank=2;s.target=9;s=act(s,{type:'stop'});assert.equal(s.phase,'won');assert.equal(s.bank,10);assert.throws(()=>act(s,{type:'stop'}));let mid=pair(fixture(['fish','fish']),1,2);mid.round=5;assert.equal(act(mid,{type:'stop'}).phase,'stakes');let t=fixture(['rice']);t.target=10;t=act(t,{type:'stop'});assert.equal(t.reason,'target');});
test('new games start at eight over ten tables; ongoing five-table saves extend without resetting play',()=>{let s=newRun(2);assert.equal(s.target,8);assert.equal(s.maxRounds,10);s.maxRounds=5;s.round=3;s.bank=17;const r=restore(JSON.stringify(s));assert.equal(r.maxRounds,10);assert.equal(r.round,3);assert.equal(r.bank,17);assert.deepEqual(r.draw,s.draw);s.phase='won';assert.equal(restore(JSON.stringify(s)).phase,'won');assert.equal(restore(JSON.stringify(s)).maxRounds,5);});
test('all 20 die outcomes are uniform in a fixed sample and use correct reward bands',()=>{const counts=Array(20).fill(0);for(let seed=0;seed<6000;seed++){let s=dicePractice();s.rng=seed;s=act(s,{type:'roll'});const d=s.dice.result;counts[d.total-1]++;assert.equal(d.locked,d.total===1||d.total===20);assert.equal(d.tier,d.total===1?'criticalLow':d.total===20?'criticalHigh':d.total<=5?'low':d.total>=15?'high':'steady');}assert.ok(counts.every(n=>n>230&&n<370));});
test('natural 1 and 20 cannot reroll even after reload; other results allow one retry',()=>{for(const n of [1,20])assert.throws(()=>act(restore(JSON.stringify(rolled(n))),{type:'roll'}),/rollLimit/);let s=act(rolled(7),{type:'roll'});assert.equal(s.dice.rolls.length,2);assert.throws(()=>act(s,{type:'roll'}));});
test('accept changes only target and accepted rewards, never banked player points',()=>{for(let n=1;n<=20;n++){let s=rolled(n);const r=act(s,{type:'acceptDice',boon:'sauce'});assert.equal(r.target,INITIAL_TARGET+n);assert.equal(r.bank,s.bank);assert.equal(r.cards.length,20+(n===1?3:n<=5?1:0));assert.throws(()=>act(r,{type:'acceptDice',boon:'sauce'}));}});
test('natural 20 gives a temporary pair and two singles worth 12 and does not fire pair listeners',()=>{let s=next(route(act(rolled(20),{type:'acceptDice'})));assert.equal(score(s),12);assert.equal(s.cards.filter(c=>c.temporary&&typeOf(c)==='food').length,4);assert.equal(s.draw.length,s.cards.filter(c=>!c.temporary).length);assert.equal(s.log.filter(e=>e.key==='pair').length,0);assert.equal(s.flips,0);assert.throws(()=>act(s,{type:'stop'}));});
test('high-roll sauce gives 2 points, and one temporary pair reward expires before draft',()=>{let s=next(route(act(rolled(18),{type:'acceptDice',boon:'sauce'})));assert.equal(score(s),2);s.flips=1;s.target=0;s=act(s,{type:'stop'});s=draft(s);assert.ok(!s.cards.some(c=>c.temporary));});
test('save version preserves choices, deck order, payment history and future randomness',()=>{let s=practiceRun();s=act(s,{type:'use',uid:3,target:4});const r=restore(JSON.stringify(s));assert.deepEqual(r,s);assert.deepEqual(draw(r),draw(s));assert.equal(restore('{'),null);assert.equal(restore(JSON.stringify({...s,version:3})),null);});
test('all 80 card effects are one concise sentence without next-card lottery conditions',()=>{assert.equal(Object.keys(CARDS).length,80);for(const def of Object.values(CARDS)){for(const text of def.text)assert.ok((text.match(/[。.!?]/g)||[]).length<=1,def.name+': '+text);assert.ok(!def.text[0].includes('下一张若'));assert.ok(def.text[0].length<=36);}});
test('d20 geometry has 20 triangular faces, 30 shared edges and opposite numbers sum 21',()=>{assert.equal(vertices.length,12);assert.equal(faces.length,20);const edges=new Map();for(const f of faces){for(let i=0;i<3;i++){const k=[f.ids[i],f.ids[(i+1)%3]].sort((a,b)=>a-b).join(',');edges.set(k,(edges.get(k)||0)+1);}const opposite=faces.find(g=>f.normal.reduce((n,x,i)=>n+x*g.normal[i],0)<-.999);assert.equal(f.value+opposite.value,21);const m=orientation(f.value);assert.ok(Math.abs(m[2].reduce((n,x,i)=>n+x*f.normal[i],0)-1)<1e-8);}assert.equal(edges.size,30);assert.ok([...edges.values()].every(n=>n===2));});
test('table shrinks before pages, keeps every identity once and has at most four rows',()=>{for(const [w,h]of [[1080,350],[1580,520],[360,220]])for(const n of [0,5,16,30,80,200]){const cards=Array.from({length:n},(_,i)=>({uid:i+1,tapped:i%4===0})),l=arrangeCards(cards,w,h);assert.deepEqual(l.pages.flat(2),cards.map(c=>c.uid));assert.ok(l.pages.every(r=>r.length<=4));assert.ok(l.rowH*l.pages[0].length<=h+1);if(l.pages.length>1)assert.equal(l.pages[0].length,4);}});
