const food = (name, text, extra={}) => ({type:'food',name,text,color:'#dec79d',...extra});
const tool = (name, text, extra={}) => ({type:'tool',name,text,color:'#afc5be',...extra});
const device = (name, text) => ({type:'device',name,text,color:'#c8c69e',scoring:true});
const trouble = (name, text, extra={}) => ({type:'trouble',name,text,color:'#be9b91',...extra});
export const EXTRA_CARDS = {
 dumpling:food(['饺子','Dumpling'],['配对：这两张牌各额外获得2分。','Pair: both cards gain 2 extra points.']),
 egg:food(['鸡蛋','Egg'],['被消耗：生成1张临时饭团。','Consumed: create one temporary Rice ball.']),
 mushroom:food(['蘑菇','Mushroom'],['配对：清理所有残渣。','Pair: clear all Residues.']),
 lemon:food(['柠檬','Lemon'],['配对：本桌查看不受浓雾与杂音影响。','Pair: your peeks ignore Fog and Interference this table.']),
 shrimp:food(['虾仁','Shrimp'],['配对：从牌组外3件工具中选1件临时上桌。','Pair: choose one of three tools outside your deck to put in play temporarily.']),
 noodle:food(['面条','Noodles'],['配对：本桌每件已横置工具额外计1分。','Pair: each exhausted tool scores 1 extra point this table.']),
 cheese:food(['奶酪','Cheese'],['配对：临时复制1张未配对食材的原版。','Pair: create a temporary base copy of one unpaired food.'],{pairTarget:'food'}),
 chili:food(['辣椒','Chili'],['配对：恢复所有工具。','Pair: ready all tools.']),
 coffee:food(['咖啡','Coffee'],['翻出：恢复最早入桌的已横置工具。','Reveal: ready the exhausted tool that entered earliest.']),
 cake:food(['蛋糕','Cake'],['不可配对，每对桌面食材使此牌计2分。','Cannot pair; this scores 2 per food pair in play.'],{noPair:true}),
 salad:food(['沙拉','Salad'],['不可配对，每种桌面食材使此牌计1分。','Cannot pair; this scores 1 per distinct food in play.'],{noPair:true}),
 marshmallow:food(['棉花糖','Marshmallow'],['不可配对，桌上仅1张同名牌时计6分。','Cannot pair; scores 6 if it is the only Marshmallow in play.'],{noPair:true}),
 cookie:food(['曲奇','Cookie'],['不可配对，同名数量为奇数时每张计3分。','Cannot pair; each scores 3 if the number of Cookies is odd.'],{noPair:true}),
 skewer:food(['竹签串','Skewer'],['不可配对，垃圾桶每张已消耗食材使此牌计1分。','Cannot pair; scores 1 per consumed food in the discard pile.'],{noPair:true}),
 pear:food(['梨','Pear'],['被消耗：查看2张。','Consumed: peek two.']),
 tofu:food(['豆腐','Tofu'],['配对：下一次生成临时食材时多生成1张。','Pair: the next temporary food you create gets one extra copy.']),
 icecream:food(['冰淇淋','Ice cream'],['不可配对，6分，每次翻牌使此牌减少1分。','Cannot pair; starts at 6 and loses 1 per later reveal.'],{noPair:true}),
 sushi:food(['寿司','Sushi'],['配对：生成1张临时鱼干。','Pair: create one temporary Dried fish.']),
 grill:tool(['烤架','Grill'],['使用：消耗1张散食材，此牌获其双倍分并生成1残渣。','Use: consume one unpaired food; this gains twice its score and creates one Residue.'],{target:'food',scoring:true}),
 steamer:tool(['蒸笼','Steamer'],['使用：让1张散食材下次被消耗时留在桌上。','Use: one unpaired food stays in play the next time it would be consumed.'],{target:'food'}),
 cleaver:tool(['菜刀','Cleaver'],['使用：消耗1对食材，生成3张临时饭团。','Use: consume one food pair to create three temporary Rice balls.'],{target:'pair'}),
 scoop:tool(['漏勺','Slotted spoon'],['使用：取回1张本桌消耗过的食材。','Use: reclaim one food consumed this table.'],{target:'consumed'}),
 compostfork:tool(['堆肥叉','Compost fork'],['使用：消耗所有残渣，此牌每张获得2分。','Use: consume all Residues; this gains 2 points per Residue.'],{scoring:true}),
 stamp:tool(['回炉印','Reheat stamp'],['使用：消耗2分装袋分数，使1张散牌重新可配对。','Use: consume 2 banked points to let one previously paired, unpaired food pair again.'],{target:'spentPair',bankCost:2}),
 magnifier:tool(['探针','Probe'],['使用：查看牌堆第3张。','Use: peek at the third card of the draw pile.']),
 fan:tool(['排风扇','Fan'],['使用：清理所有浓雾与杂音。','Use: clear all Fog and Interference.']),
 washbucket:tool(['洗涤桶','Wash bucket'],['使用：消耗3分装袋分数，清理所有麻烦。','Use: consume 3 banked points to clear all trouble.'],{bankCost:3}),
 tray:tool(['回菜盘','Return tray'],['使用：将1张散食材放到剩余牌堆底。','Use: put one unpaired food on the bottom of the draw pile.'],{target:'food'}),
 menu:tool(['招牌菜单','House menu'],['使用：选择1种桌面食材，使桌上同名食材各获1分。','Use: choose a food in play; each food of that name in play gains 1 point.'],{target:'foodKind'}),
 magnet:tool(['磁铁','Magnet'],['使用：取回1件弃置的工具，保持横置。','Use: reclaim one discarded tool exhausted.'],{target:'discardTool'}),
 whetstone:tool(['磨刀石','Whetstone'],['使用：让另1件就绪工具再使用2次后才横置。','Use: one other ready tool exhausts after its next two uses.'],{target:'readyTool'}),
 ladle:tool(['采购袋','Shopping bag'],['使用：消耗4分装袋分数，将1张临时食材收入牌组。','Use: consume 4 banked points to make one temporary food permanent.'],{target:'temporaryFood',bankCost:4}),
 picnic:device(['野餐篮','Picnic basket'],['桌面每种食材的首对，使此牌计2分。','This scores 2 for each distinct kind of food pair in play.']),
 pantry:device(['储物柜','Pantry'],['每张未配对的非临时食材使此牌计1分。','This scores 1 per unpaired permanent food in play.']),
 servingbell:device(['出餐铃','Service bell'],['每生成1张临时食材，此牌获得1分。','Whenever a temporary food is created, this gains 1 point.']),
 choppingboard:device(['砧板','Chopping board'],['每消耗1张食材，此牌获得2分。','Whenever a food is consumed, this gains 2 points.']),
 spicejar:device(['香料罐','Spice jar'],['每清理1张麻烦，最早入桌的散食材获得1分。','Whenever trouble is cleared, the earliest unpaired food gains 1 point.']),
 timer:device(['计时器','Kitchen timer'],['每次使用工具，此牌获得1分。','Whenever you use a tool, this gains 1 point.']),
 recyclingbag:device(['回收袋','Recycling sack'],['垃圾桶中每张麻烦使此牌计1分。','This scores 1 per trouble card in the discard pile.']),
 glasscase:device(['展示柜','Display case'],['每张桌面临时食材使此牌计1分。','This scores 1 per temporary food in play.']),
 grease:trouble(['积垢','Grime'],['每次使用工具，此牌额外扣1分。','Whenever you use a tool, this scores 1 fewer point.'],{scoring:true}),
 clutter:trouble(['杂物','Clutter'],['桌面每件工具使此牌扣1分。','This scores minus 1 per tool in play.'],{scoring:true}),
 flies:trouble(['果蝇','Fruit flies'],['临时食材不计分。','Temporary food scores zero.']),
 cold:trouble(['冷灶','Cold stove'],['食材牌面上的配对能力失效。','Printed food pair abilities are disabled.']),
};
export const EXTRA_PACKAGES = [
 ['dumpling',['dumpling','dumpling','cold']],['egg',['egg','egg','juicer','flies']],
 ['mushroom',['mushroom','mushroom','paper']],['lemon',['lemon','lemon','fog']],
 ['shrimp',['shrimp','shrimp','clutter']],['noodle',['noodle','noodle','rust']],
 ['cheese',['cheese','cheese','debt']],['chili',['chili','chili','grease']],
 ['coffee',['coffee','mint','rust']],['cake',['cake','rice','cold']],
 ['salad',['salad','sushi','wrap']],['marshmallow',['marshmallow','paper']],
 ['cookie',['cookie','cookie','cookie','paper']],['skewer',['skewer','egg','oil']],
 ['pear',['pear','scope','fog']],['tofu',['tofu','tofu','flies']],
 ['icecream',['icecream','noise']],['sushi',['sushi','sushi','debt']],
 ['grill',['grill','pear','grease']],['steamer',['steamer','egg','clutter']],
 ['cleaver',['cleaver','rice','cold']],['scoop',['scoop','juicer','flies']],
 ['compostfork',['compostfork','grill','rust']],['stamp',['stamp','toast','debt']],
 ['magnifier',['magnifier','fog']],['fan',['fan','lemon','noise']],
 ['washbucket',['washbucket','oil']],['tray',['tray','coffee','paper']],
 ['menu',['menu','cola','clutter']],['magnet',['magnet','sifter','rust']],
 ['whetstone',['whetstone','torch','grease']],['ladle',['ladle','wish','flies']],
 ['picnic',['picnic','wild','wrap']],['pantry',['pantry','rice','debt']],
 ['servingbell',['servingbell','tofu','flies']],['choppingboard',['choppingboard','egg','oil']],
 ['spicejar',['spicejar','cloth','cold']],['timer',['timer','torch','grease']],
 ['recyclingbag',['recyclingbag','mushroom','paper']],['glasscase',['glasscase','popcorn','flies']],
].map(([id,cards])=>({id,cards,name:EXTRA_CARDS[id].name}));
