import {GROWTH_ROUTES,GROWTH_CARDS,GROWTH_RELICS,growthRoute,growthProgress,growthCurve} from './growth-lab.js';
import {DIFFICULTIES} from './unlock-data.js';
import {icon} from './cards.js';
export function growthMenu(lang,curve,difficulty=0){
 const en=lang==='en',tx=a=>a[en?1:0];
 return `<div class="growth-intro"><p>${en?'Growth lasts for this run, including optional endless play. Separate test save.':'成长保留到本局结束，通关十桌可继续无限。使用独立存档。'}</p><div class="growth-curves">${['rising','classic'].map(id=>`<button data-action="growth-curve" data-id="${id}" aria-pressed="${id===curve}">${id==='rising'?(en?'Rising targets':'成长目标'):(en?'Original targets':'原版目标')}</button>`).join('')}</div><p>${curve==='rising'?(en?`Target raises: dice total × ${growthCurve(difficulty).join(' / ')}. Bank carries forward. Beyond table ten, the cumulative target doubles every table.`:`第2–10桌加码：骰点合计 × ${growthCurve(difficulty).join('／')}。装袋分数保留；第10桌后，无限模式每桌累计目标翻倍。`):(en?'Use the existing target curve to compare growth alone.':'沿用现有目标曲线，单独比较养成收益。')}</p><h3>${en?'STAKES':'进阶'}</h3><div class="event-mode-options">${DIFFICULTIES.map((d,i)=>`<button data-action="growth-difficulty" data-id="${i}" aria-pressed="${i===difficulty}">${i}. ${tx(d.name)}</button>`).join('')}</div><p>${tx(DIFFICULTIES[difficulty].text)}</p></div><div class="growth-route-grid">${Object.entries(GROWTH_ROUTES).map(([id,r])=>`<article class="growth-route"><div class="growth-fan">${icon(r.core)}${icon(r.support)}${icon('relic-'+r.relic)}</div><h3>${tx(r.name)}</h3><p>${tx(r.text)}</p><dl><dt>${tx(GROWTH_CARDS[r.core].name)}</dt><dd>${tx(GROWTH_CARDS[r.core].text)}</dd><dt>${tx(GROWTH_CARDS[r.support].name)}</dt><dd>${tx(GROWTH_CARDS[r.support].text)}</dd><dt>${tx(GROWTH_RELICS[r.relic].name)}</dt><dd>${tx(GROWTH_RELICS[r.relic].text)}</dd></dl><button class="primary" data-action="growth-start" data-id="${id}">${en?'Play this deck':'用这套开局'}</button></article>`).join('')}</div><p class="growth-entry">${en?'New: after tables 1, 3, 5, 7 and 9, the Staple stand can bind 3 random cards for 4 banked points. Trouble can be picked; bombs cannot.':'新事件：第1、3、5、7、9桌后，装订摊可消耗4分随机装订3张牌；麻烦可能入选，炸弹除外。'}</p><details class="growth-rules"><summary>${en?'Growth rules':'成长规则'}</summary><ul><li>${en?'20-card starter: two cores, one support and its pledged item. The first card of table 1 is a core; later tables shuffle normally.':'20张预组牌，含2张核心、1张辅助牌及对应抵押物。第1桌首张为核心，后续正常洗牌。'}</li><li>${en?'Owned permanent cores track growth from acquisition, including in the draw and discard piles. No progress is retroactive.':'永久核心从获得时开始记录成长，在牌库和弃牌堆也生效，不补算获得前的进度。'}</li><li>${en?'The same food consumed or trouble cleared counts once per table; each exact pair counts once per table. Different pair kinds are counted across the run.':'同一食材的消耗、同一麻烦的清理、同一对实体牌的配对，每桌各计一次；不同配对种类按整局记录。'}</li><li>${en?'Ordinary copies start at base score. Only Sample bottle copies growth. Temporary copies do not grow; permanent copies can.':'普通复制从原版开始，仅留样瓶继承成长；临时牌不继续成长，转为永久牌后可以成长。'}</li><li>${en?'Each core can double 10 times in the first ten tables; endless unlocks two more levels per table. Bombs still end the run.':'前十桌核心上限10级；无限模式每桌再开放2级。翻出炸弹仍立即结束整局。'}</li></ul></details>`;
}
export function growthJournal(s,lang){
 const en=lang==='en';
 if(!s?.growth)return `<p>${en?'Choose a deck to begin.':'先选择一套牌组开局。'}</p>`;
 return `<p>${en?'Table':'第'} ${s.round} / ${s.endless?'∞':10} · ${GROWTH_ROUTES[s.growth.route].name[en?1:0]} · ${en?'Seed':'种子'} ${s.seed}</p><div class="growth-journal">${s.cards.filter(c=>!c.temporary&&growthRoute(c)).map(c=>`<article>${icon(c.original)}<div><h3>${GROWTH_CARDS[c.original].name[en?1:0]} <small>#${c.uid}</small></h3><p>${growthProgress(c,lang,s)}</p><small>${c.zone==='deck'?(en?'In deck':'牌库'):c.zone==='table'?(en?'On table':'桌面'):(en?'Discarded':'弃牌堆')}</small></div></article>`).join('')}</div>`;
}
