import {ACHIEVEMENTS} from './progress.js';
import {CARDS,RELICS,icon} from './cards.js';
import {UNLOCKS,CARD_BACKS,DIFFICULTIES,CHALLENGES,unlockSet,maxDifficulty,unlockRequirement} from './unlock-data.js';
import {posterBack} from './poster-art.js';
export function lockLabel(meta,id,type,lang){
 const key=unlockRequirement(id,type);return key&&!meta.achievements?.[key]?(lang==='en'?'Unlock: ':'解锁：')+ACHIEVEMENTS[key].text[lang==='en'?1:0]:'';
}
export function journalHTML(meta,prefs){
 const en=prefs.lang==='en',tx=x=>x[en?1:0],tr=(a,b)=>en?b:a,backs=unlockSet(meta,'backs');
 const rewardNames=r=>[...(r.cards||[]).map(id=>tx(CARDS[id].name)),...(r.relics||[]).map(id=>tx(RELICS[id].name)),...(r.backs||[]).map(id=>tx(CARD_BACKS[id])+tr('卡背',' card back')),...(r.challenges||[]).map(id=>tx(CHALLENGES[id].name)),...(r.art||[]).map(()=>tr('旧版卡图','Original artwork'))].join(' · ');
 return `<p class="journal-intro">${tr('新卡牌与抵押物从下一局加入卡池。解锁不提供永久分数加成。','New cards and pledged items enter the pool next run. Unlocks add no permanent score bonuses.')}</p><h3>${tr('里程碑','MILESTONES')}</h3><div class="milestone-grid">${Object.entries(ACHIEVEMENTS).map(([id,a])=>`<article class="milestone ${meta.achievements?.[id]?'unlocked':''}"><b>${meta.achievements?.[id]?'◆':'◇'} ${tx(a.name)}</b><p>${tx(a.text)}</p>${UNLOCKS[id]?`<small>${rewardNames(UNLOCKS[id])}</small>`:''}</article>`).join('')}</div><h3>${tr('卡背','CARD BACKS')}</h3><div class="back-gallery">${Object.entries(CARD_BACKS).map(([id,n])=>{const open=id==='casino'||backs.has(id);return `<button data-action="card-back" data-id="${id}" ${open?'':'disabled'} aria-pressed="${(prefs.cardBack||'casino')===id}">${posterBack(id)}<b>${tx(n)}</b><small>${open?((prefs.cardBack||'casino')===id?tr('使用中','Selected'):tr('使用','Use')):lockLabel(meta,id,'backs',prefs.lang)}</small></button>`;}).join('')}</div><h3>${tr('最近牌局','RECENT RUNS')}</h3><div class="run-history">${(meta.history||[]).map(r=>`<p><b>${r.reason==='complete'?tr('通关','CLEARED'):r.reason==='bomb'?tr('爆炸','BUST'):tr('未达标','SHORT')}</b><span>${tr('第','Table ')}${r.round}${tr('桌','')} · ${r.bank} / ${r.target}</span><small>${tx(DIFFICULTIES[r.difficulty||0].name)} · ${tx(CHALLENGES[r.challenge||'standard'].name)}</small></p>`).join('')||`<p>${tr('完成一局后留下记录。','Finish a run to leave a record.')}</p>`}</div>`;
}
export function runSetupHTML(meta,prefs){
 const en=prefs.lang==='en',tx=x=>x[en?1:0],tr=(a,b)=>en?b:a,level=maxDifficulty(meta),challenges=unlockSet(meta,'challenges');
 return `<h3>${tr('进阶','STAKES')}</h3><div class="run-options">${DIFFICULTIES.map((d,i)=>`<button data-action="difficulty" data-id="${i}" aria-pressed="${(prefs.difficulty||0)===i}" ${i>level?'disabled':''}><b>${i}. ${tx(d.name)} ${meta.ascensionWins?.[i]?'◆':''}</b><span>${tx(d.text)}</span>${i>level?`<small>${tr('通关上一级常规牌局解锁','Clear the previous stakes on Standard')}</small>`:''}</button>`).join('')}</div><h3>${tr('挑战','CHALLENGES')}</h3><div class="run-options">${Object.entries(CHALLENGES).map(([id,c])=>`<button data-action="challenge" data-id="${id}" aria-pressed="${(prefs.challenge||'standard')===id}" ${id==='standard'||challenges.has(id)?'':'disabled'}><b>${tx(c.name)} ${meta.challengeWins?.[id]?'◆':''}</b><span>${tx(c.text)}</span><small>${lockLabel(meta,id,'challenges',prefs.lang)}</small></button>`).join('')}</div><p>${tr('下次入座生效；当前牌局保持原规则。','Applies to your next run. Your current run keeps its rules.')}</p>`;
}
