import { BOONS, CARDS, RELICS, PACKAGES, VERSION, icon, nameOf, typeOf } from './cards.js';
import { onTable, card, score, value, partners, paidFoods } from './engine.js';
import { dieHTML } from './d20.js';

export function renderView({s,screen,prefs,selected,flow,busy,performance,boonChoice,inspect,saved,diceInHand}){
 const en=prefs.lang==='en',tr=(a,b)=>en?b:a,tx=a=>a[en?1:0],name=k=>nameOf(k,prefs.lang),esc=v=>String(v).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
 const btn=(action,label,attrs='',disabled=false,cls='')=>`<button data-action="${action}" ${attrs} ${disabled||busy?'disabled':''} class="${cls}">${label}</button>`;
 const types={food:tr('食材','FOOD'),tool:tr('工具','TOOL'),device:tr('装置','DEVICE'),trouble:tr('麻烦','TROUBLE'),bomb:tr('炸弹','BOMB')};
 const mini=k=>`<span class="mini">${icon(k)}<span>${name(k)}</span></span>`;
 function header(){return `<header class="top"><button class="brand" data-action="home"><span class="wordmark">One More<span>?</span></span><small>v${VERSION}</small></button><nav>${btn('catalog',tr('牌组','Cards'))}${btn('rules','?',`aria-label="${tr('规则','Rules')}"`)}${btn('sound',prefs.sound?'♪':'♩',`aria-label="${tr('声音','Sound')}"`)}${btn('motion',prefs.motion?'▷':'Ⅱ',`aria-label="${tr('动画','Motion')}"`)}${btn('language',en?'中文':'EN')}${btn('fullscreen','⤢',`aria-label="${tr('全屏','Fullscreen')}"`)}${screen!=='home'?btn('home',tr('离桌','Leave')):''}</nav></header>`;}
 function home(){return `<main class="salon"><div class="salon-felt"><div class="menu-cards menu-cards-left">${['fish','tea','wild'].map((k,i)=>`<div class="menu-card" style="--i:${i}">${icon(k)}<b>${name(k)}</b></div>`).join('')}</div><section class="main-menu"><h1 class="wordmark">One More<span>?</span></h1>${btn('new',tr('入座','Play'),'id="new"',false,'primary menu-play')}${saved&&['play','stakes','draft'].includes(saved.phase)?btn('continue',tr('继续','Continue'),' ',false,'menu-continue'):''}<div class="menu-secondary">${btn('practice',tr('练习','Practice'))}${btn('dice-practice','d20')}</div><details class="starter"><summary>${tr('起始牌组','Starting deck')}</summary>${btn('classic',tr('基础','Classic'))}${btn('mixed',tr('发酵','Ferment'))}</details></section><div class="menu-cards menu-cards-right">${['torch','jar','timetable'].map((k,i)=>`<div class="menu-card" style="--i:${i}">${icon(k)}<b>${name(k)}</b></div>`).join('')}</div></div></main>`;}
 function tile(c){
  const matches=partners(s,c.uid).length>0,angle=c.uid*37%9-4,target=flow?.choices.some(x=>x.id===c.uid),next=['stove','relay','candle','wish','timetable','wrap','rust'].includes(c.kind);
  const badge=c.ferment?tr('发酵','FERMENT'):c.sealedBy?tr('封存','SEALED'):c.pair?`♥ ${c.pair}`:c.tapped?'↷':c.freeCost?tr('免费','FREE'):next?(c.triggers?'✓':tr('下一张','NEXT')):c.temporary?tr('临时','LOAN'):matches?'♥':types[typeOf(c)];
  return `<div class="card-seat ${c.tapped?'landscape':''}" style="--offset:${c.uid*13%7-3}px"><button class="tile ${typeOf(c)} ${selected===c.uid?'selected':''} ${c.pair?'paired':''} ${c.tapped?'tapped':''} ${c.sealedBy?'sealed':''} ${target?'targetable':''}" data-action="select" data-uid="${c.uid}" data-angle="${angle}" style="--tilt:${angle}deg;${performance==='draw'&&c.uid===s.table.at(-1)?'visibility:hidden;':''}" aria-label="${esc(name(c.kind)+' · '+badge)}" aria-pressed="${selected===c.uid}"><span class="tile-top"><span>${types[typeOf(c)]}</span>${typeOf(c)==='food'?`<b>${value(s,c)}</b>`:''}</span>${icon(c.kind)}<strong>${name(c.kind)}</strong><span class="tile-badge ${matches?'match':''}">${badge}</span></button></div>`;
 }
 function preview(){return `<div class="preview"><div class="preview-line">${s.draw.slice(0,3).map((uid,i)=>{const c=card(s,uid),known=s.known.includes(uid);return `<div class="preview-slot ${known?'known':''} ${known&&c.kind==='bomb'?'danger':''}" title="${known?esc(tx(CARDS[c.kind].text)):''}"><small>${i+1}</small>${known?icon(c.kind):'<b>?</b>'}${known?`<span>${name(c.kind)}</span>`:''}</div>`;}).join('')}</div></div>`;}
 function relicDisabled(id){return s.phase!=='play'||s.relicUsed[id]||flow||id==='lunchbox'||id==='shaker'&&!s.flips||id==='recycler'&&!paidFoods(s).length||id==='splitter'&&!onTable(s).some(c=>c.pair);}
 function game(){const earned=score(s),need=Math.max(0,s.target-s.bank-earned);return `<main class="game-room"><aside class="score-rail"><div class="round-plaque"><span>${s.practice?tr('练习','PRACTICE'):tr('台','TABLE')}</span><b>${String(s.round).padStart(2,'0')}</b><small>/ ${s.maxRounds}</small></div><div class="score-box target-score"><small>${tr('目标','TARGET')}</small><strong>${s.target||'—'}</strong><div class="meter"><i style="width:${s.target?Math.min(100,(s.bank+earned)/s.target*100):100}%"></i></div></div><div class="score-box"><small>${tr('装袋','BANKED')}</small><strong>${s.bank}</strong></div><div class="score-box table-score"><small>${tr('桌面','TABLE')}</small><strong>${earned}</strong></div><p class="target-note ${need?'':'beaten'}">${need?tr(`差 ${need}`,`${need} TO GO`):'✓'}</p>${s.nextEffects.length?`<div class="next-effect">${s.nextEffects.map(e=>mini(e.kind)).join('')}<span>→</span></div>`:''}${s.boon?`<div class="boon-badge" title="${esc(tx(BOONS[s.boon].text))}">${tx(BOONS[s.boon].name)}${s.boon==='meal'?` · ${s.freePayments}`:''}</div>`:''}<div class="rail-bottom">${btn('catalog',`${s.cards.filter(c=>!c.temporary).length} ▧`)}${btn('log','≡',`aria-label="${tr('记录','Log')}"`)}</div></aside><div class="casino"><div class="relic-rack">${s.relics.map(id=>btn('relic',`${icon(RELICS[id].icon)}<span>${tx(RELICS[id].name)}<small>${s.relicUsed[id]?'—':id==='lunchbox'?'∞':'1'}</small></span>`,`data-id="${id}" title="${esc(tx(RELICS[id].text))}"`,relicDisabled(id),'relic-token')).join('')}</div><section class="casino-table"><div class="table-engraving" aria-hidden="true"><svg viewBox="0 0 700 180"><defs><path id="table-arc" d="M 60 135 Q 350 -40 640 135"/></defs><text><textPath href="#table-arc" startOffset="50%" text-anchor="middle">ONE MORE?</textPath></text></svg></div><div class="dealer-strip">${preview()}<div></div><div class="deck-station"><button id="deck-draw" class="card-back" data-action="draw" ${flow||busy?'disabled':''} aria-label="${tr('翻牌','Draw')}"><span>?</span><small>ONE MORE</small></button><span class="deck-count">${s.draw.length}</span></div></div><div class="card-field">${onTable(s).map(tile).join('')}</div><div class="table-actions">${btn('stop',`${tr('收摊','CASH OUT')}<strong>${earned}</strong>`,'id="stop"',!s.flips||!!flow,'cash-action')}<div class="table-pager"></div>${btn('draw','ONE MORE?','id="draw"',!!flow,'primary draw-action')}</div></section><div class="action-tray">${inspect}</div></div></main>`;}
 function stakes(){const d=s.dice.result,rolling=busy&&performance==='dice',visible=d&&!rolling,canRoll=!d||!d.locked&&s.dice.rolls.length<2,hand=diceInHand&&canRoll&&!rolling;
  const effects=visible?d.tier==='criticalLow'?['debt','rust','paper']:d.tier==='low'?['paper']:[]:[];
  return `<main class="stakes-shell"><div class="stakes-heading"><p class="eyebrow">${tr(`第 ${s.round+1} 台`,`TABLE ${s.round+1}`)}</p><h1>d20</h1></div><section class="d20-panel"><div class="dice-tray" id="dice-tray"><div class="tray-lining"></div><button class="tray-die-button" data-action="${hand?'throw-die':'pick-die'}" ${!canRoll||busy?'disabled':''} aria-label="${tr(hand?'掷入骰盘':'拿起骰子',hand?'Throw into tray':'Pick up die')}">${(!hand&&d)||rolling?dieHTML(d?.total||20,'tray'):''}</button><div class="tray-brand">ONE MORE?</div></div><div class="dice-controls"><div class="dice-hand-place">${hand?btn('shake-die',dieHTML(20,'hand'),'id="die-hand" aria-label="'+tr('摇骰；拖入骰盘','Shake die; drag into tray')+'"',false,'die-hand'):''}</div><div class="dice-result"><strong>${visible?`+${d.total}`:'—'}</strong><span>${visible?`${s.target} → ${s.target+d.total}`:''}</span>${d?.locked?`<small>${tr('锁定','LOCKED')}</small>`:''}</div><div class="dice-main-buttons">${hand?btn('throw-die',tr('掷出','THROW'),'id="roll"',false,'primary'):canRoll?btn('pick-die',tr('重掷','REROLL'),'id="reroll"',false,'outline'):''}${visible?btn('acceptDice',tr('收下','ACCEPT'),'id="accept-dice"',false,'primary'):''}</div></div><div class="dice-reward">${effects.length?effects.map(k=>`<span class="reward-card">+ ${mini(k)}</span>`).join(''):visible&&d.tier==='criticalHigh'?`<strong>♛ ${tx(BOONS.feast.name)}</strong><span>${tx(BOONS.feast.text)}</span>`:''}</div>${visible&&d.tier==='high'?`<div class="boon-choices">${['scout','sauce','meal'].map(id=>btn('boon',`${icon(BOONS[id].icon)}<span>${tx(BOONS[id].name)}<small>${tx(BOONS[id].text)}</small></span>`,`data-id="${id}" aria-pressed="${boonChoice===id}"`,false,boonChoice===id?'boon-choice chosen':'boon-choice')).join('')}</div>`:''}</section></main>`;
 }
 function draft(){const groups={};for(const c of s.cards.filter(c=>!c.temporary))(groups[c.original]??=[]).push(c);return `<main class="draft-shell"><div class="receipt-head"><h1>${tr('换桌','NEXT TABLE')}</h1><p>${s.bank} / ${s.target}${s.nextBoon?` · ${tx(BOONS[s.nextBoon].name)}`:''}</p></div><div class="draft-heading"><h2>${tr('添牌','ADD')}</h2><span>${s.added?'0 / 1':'1 / 1'}</span></div><div class="package-grid">${s.offers.map(id=>{const p=PACKAGES.find(p=>p.id===id);return `<article class="package"><h3>${tx(p.name)}</h3><div class="pack-fan">${p.cards.map((k,i)=>`<span style="--i:${i}">${icon(k)}</span>`).join('')}</div>${p.cards.map(k=>`<div class="package-card"><strong>${name(k)}</strong><p>${tx(CARDS[k].text)}</p></div>`).join('')}${btn('add',tr('选择','TAKE'),`data-id="${id}"`,s.added,'outline')}</article>`;}).join('')}</div>${s.relicOffer.length?`<div class="draft-heading"><h2>${tr('遗物','RELIC')}</h2></div><div class="package-grid">${s.relicOffer.map(id=>`<article class="package"><h3>${tx(RELICS[id].name)}</h3><p>${tx(RELICS[id].text)}</p>${btn('chooseRelic',tr('选择','TAKE'),`data-id="${id}"`,s.relicPicked)}</article>`).join('')}</div>`:''}<div class="draft-heading"><h2>${tr('删牌','REMOVE')}</h2><span>${s.removed?'0 / 1':'1 / 1'}</span></div><div class="remove-list">${Object.entries(groups).map(([k,a])=>btn('remove',`${name(k)} ×${a.length}`,`data-uid="${a[0].uid}"`,s.removed||k==='bomb'||s.cards.length<=2)).join('')}</div><div class="draft-footer"><span>${s.cards.length} ▧</span>${btn('next',tr('下一桌 →','NEXT →'),'id="next"',!!s.relicOffer.length&&!s.relicPicked,'primary')}</div></main>`;}
 function result(){const bomb=s.reason==='bomb';return `<main class="result"><div class="result-art">${icon(bomb?'bomb':'candle')}</div><h1>${bomb?tr('爆炸','BUST'):s.phase==='won'?tr('通关','CLEARED'):tr('未达标','SHORT')}</h1><div class="result-stats"><div><small>${tr('装袋','BANKED')}</small><b>${s.bank}</b></div><div><small>${tr('目标','TARGET')}</small><b>${s.target}</b></div></div><div class="result-buttons">${btn(s.practice?'new':'retry','One More?','',false,'primary')}${btn('home',tr('离桌','LEAVE'))}</div></main>`;}
 return header()+(screen==='home'||!s?home():performance==='draw'||s.phase==='play'?game():s.phase==='stakes'?stakes():s.phase==='draft'?draft():result());
}
