import {SKIP_REWARDS,wheelSections} from './momentum.js';
import {icon} from './cards.js';
const colors=['#574798','#339563','#ff4928','#81b8ba','#df5196','#fff8e8','#edbd38','#161936'];
const point=(angle,r)=>{const a=(angle-90)*Math.PI/180;return [160+Math.cos(a)*r,160+Math.sin(a)*r];};
export function wheelSVG(offer,spinning=false){
 const pieces=wheelSections(offer.pool),rotation=spinning?0:offer.rotation||0;
 return `<svg class="skip-wheel" viewBox="0 0 320 320" role="img" aria-label="${offer.id&&!spinning?'Reward wheel: '+SKIP_REWARDS[offer.id].name[1]:'Reward wheel'}"><circle cx="160" cy="164" r="151" fill="#574798"/><g class="wheel-rotor" style="transform:rotate(${rotation}deg);transform-origin:160px 160px">${pieces.map(({id,start,end,mid},i)=>{const a=point(start,147),b=point(end,147),label=point(mid,120),symbol=point(mid,76),n=Object.keys(SKIP_REWARDS).indexOf(id)+1;return `<path d="M160 160L${a}A147 147 0 ${end-start>180?1:0} 1 ${b}Z" fill="${colors[n-1]}" stroke="#fff8e8" stroke-width="1"/>${end-start>20?`<svg x="${symbol[0]-18}" y="${symbol[1]-18}" width="36" height="36" viewBox="0 0 104 104" aria-hidden="true">${icon(SKIP_REWARDS[id].icon)}</svg>`:''}${end-start>9?`<text x="${label[0]}" y="${label[1]}" text-anchor="middle" dominant-baseline="central" fill="${n===6||n===7?'#161936':'#fff8e8'}" font-size="24" font-weight="900">${n}</text>`:''}`;}).join('')}</g><circle cx="160" cy="160" r="38" fill="#161936"/><circle cx="160" cy="160" r="29" fill="#fff8e8"/><text x="160" y="174" font-family="Georgia" font-size="42" text-anchor="middle" fill="#574798">?</text><path class="wheel-pointer" d="M147 3H173L160 31Z" fill="#edbd38" stroke="#161936" stroke-width="3"/></svg>`;
}
export function wheelHTML(s,lang='zh',busy=false){
 const en=lang==='en',offer=s.skipOffer;if(!offer?.pool)return '';
 const won=s.phase==='skipReward',r=SKIP_REWARDS[offer.id],sections=wheelSections(offer.pool);
 return `<div class="wheel-layout"><div class="wheel-console">${wheelSVG(offer,busy)}${won&&!busy?`<div class="wheel-result" aria-live="polite">${icon(r.icon)}<strong>${r.name[en?1:0]}</strong><p>${r.text[en?1:0]}</p></div>`:''}<button class="wheel-spin" data-action="${won?'skip-table':'spin-skip'}" ${won?`data-id="${offer.id}"`:''} ${busy?'disabled':''}>${won?(en?'CLAIM & CONTINUE':'领取并继续'):(en?'SKIP & SPIN':'跳桌 · 转动轮盘')}</button><small>${en?'Spinning commits the skip. One spin per table.':'转动即确认跳桌，每桌仅一次。'}</small></div><ol class="wheel-prizes">${sections.map(({id,chance})=>{const x=SKIP_REWARDS[id],n=Object.keys(SKIP_REWARDS).indexOf(id)+1;return `<li class="${offer.id===id&&!busy?'landed ':''}${x.rare?'wheel-rare':''}" style="--prize-color:${colors[n-1]}"><b>${n}</b><div><strong>${x.name[en?1:0]} <em>${Number(chance.toFixed(2))}%</em></strong><span>${x.text[en?1:0]}</span></div></li>`;}).join('')}</ol></div>`;
}
