import {mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {connectSmokeTransport} from './smoke-transport.mjs';
import {newRun,dicePractice,act,SAVE_KEY,PREF_KEY} from '../game/engine.js';
const t=await connectSmokeTransport(Number(process.env.EDGE_DEBUG_PORT||9227)),{send}=t,out=resolve('.artifacts/smoke-one-more-v030');await mkdir(out,{recursive:true});
const report={version:'0.3.0',checks:[],captures:[],failures:[]},wait=ms=>new Promise(r=>setTimeout(r,ms));
async function ev(expression){const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
async function idle(){for(let n=0;n<100;n++){if(await ev('document.querySelector(".brand")&&document.body.dataset.busy!=="true"'))return;await wait(40);}throw Error('UI busy');}
async function point(sel){return ev(`(()=>{const e=document.querySelector(${JSON.stringify(sel)});if(!e||e.disabled)throw Error('Unavailable '+${JSON.stringify(sel)});e.scrollIntoView({block:'nearest',inline:'nearest'});const r=e.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2;if(!e.contains(document.elementFromPoint(x,y)))throw Error('Covered '+${JSON.stringify(sel)});return {x,y};})()`);}
async function click(sel,settle=true){const p=await point(sel);await send('Input.dispatchMouseEvent',{type:'mousePressed',...p,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',...p,button:'left',clickCount:1});if(settle){await wait(35);await idle();}}
function check(label,ok,detail=null){report.checks.push({label,ok:!!ok,detail});if(!ok){report.failures.push(label);console.log('FAIL',label,detail);}}
async function capture(name){await ev('window.scrollTo(0,0)');const r=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(resolve(out,name+'.png'),Buffer.from(r.data,'base64'));report.captures.push(name);}
async function state(){return ev(`JSON.parse(localStorage.getItem(${JSON.stringify(SAVE_KEY)}))`);}
async function seed(s,lang='zh'){await ev(`localStorage.setItem(${JSON.stringify(SAVE_KEY)},${JSON.stringify(JSON.stringify(s))});localStorage.setItem(${JSON.stringify(PREF_KEY)},${JSON.stringify(JSON.stringify({lang,sound:false,motion:true}))})`);await send('Page.reload',{ignoreCache:true});await wait(130);await idle();await click('[data-action="continue"]');}
function fixture(n=5){const s=newRun(92);s.cards=[];s.table=[];s.draw=[];s.uid=0;s.flips=n;s.bank=0;const kinds=['rice','fish','mint','tea','toast','wild','torch','scope','jar','relay','candle','timetable'];for(let i=0;i<n+3;i++){const kind=i===n+2?'bomb':kinds[i%kinds.length],zone=i<n?'table':'deck';const c={uid:++s.uid,original:kind,kind,zone,tapped:i<n&&['torch','jar'].includes(kind),pair:null,pairedOnce:false,sealedBy:null,ferment:null,caught:null,paid:false,entered:i+1,triggers:0,freeCost:false,multiplier:1};s.cards.push(c);s[zone==='table'?'table':'draw'].push(c.uid);}return s;}
function rollValue(n){for(let seed=0;seed<1000;seed++){const s=dicePractice();s.practice=false;s.rng=seed;const r=act(s,{type:'roll'});if(r.dice.result.total===n)return r;}}
async function audit(label,lang){const a=await ev(`(()=>{const f=document.querySelector('.card-field'),r=f?.getBoundingClientRect(),a=document.querySelector('.table-actions'),tiles=[...document.querySelectorAll('.card-row .tile')],rects=tiles.map(e=>e.getBoundingClientRect());let overlaps=0;for(let i=0;i<rects.length;i++)for(let j=i+1;j<rects.length;j++)if(Math.min(rects[i].right,rects[j].right)-Math.max(rects[i].left,rects[j].left)>2&&Math.min(rects[i].bottom,rects[j].bottom)-Math.max(rects[i].top,rects[j].top)>2)overlaps++;return {page:document.documentElement.scrollWidth<=innerWidth+1,noScroll:!f||f.scrollHeight<=f.clientHeight+1,rows:document.querySelectorAll('.card-row').length,inside:!f||rects.every(x=>x.left>=r.left&&x.right<=r.right&&x.top>=r.top&&x.bottom<=r.bottom),separate:!f||!a||r.bottom<=a.getBoundingClientRect().top+1,overlaps,text:document.body.innerText.replace(document.querySelector('[data-action="language"]')?.innerText||'','')};})()`);
 check(label+' viewport',a.page);check(label+' table has no scrollbar',a.noScroll);check(label+' maximum four rows',a.rows<=4);check(label+' cards stay inside table',a.inside);check(label+' actions do not cover cards',a.separate);check(label+' tilted cards do not overlap',a.overlaps===0,a.overlaps);if(lang==='en')check(label+' English',!/[\u3400-\u9fff]/u.test(a.text),a.text.match(/[\u3400-\u9fff]+/gu));}
try{
 await send('Page.enable');await send('Runtime.enable');await send('Log.enable');t.errors.length=0;
 for(const v of [{width:1280,height:800,lang:'zh'},{width:1920,height:1080,lang:'en'},{width:960,height:600,lang:'zh'},{width:390,height:844,lang:'en'}]){
  const label=`${v.width}-${v.height}-${v.lang}`;await send('Emulation.setDeviceMetricsOverride',{width:v.width,height:v.height,deviceScaleFactor:1,mobile:v.width<600});await send('Page.navigate',{url:'http://127.0.0.1:8888/'});await wait(140);await idle();await seed(newRun(29),v.lang);await click('[data-action="home"]');await audit(label+' home',v.lang);await capture(label+'-home');
  await click('[data-action="new"]');await audit(label+' new',v.lang);const saved=JSON.stringify(await state());await click('[data-action="home"]');await click('[data-action="practice"]');await click('#draw');await click('.tile[data-uid="4"]');await click('[data-action="pair"]');await click('.tile[data-uid="1"]');await click('.tile[data-uid="2"]');await click('.tile[data-uid="2"]');await click('[data-action="use"]');
  check(label+' practice score 2+2',await ev('document.querySelector(".table-score strong").textContent==="4"'));check(label+' practice preserves challenge',JSON.stringify(await state())===saved);await audit(label+' combo',v.lang);await capture(label+'-combo');await click('#stop');check(label+' practice completes',await ev('!!document.querySelector(".result")'));
  const scales=[];for(const n of [16,35,150]){await seed(fixture(n),v.lang);await audit(label+' '+n+' cards',v.lang);const l=await ev('({...document.querySelector(".card-field").dataset,visible:document.querySelectorAll(".card-row .tile").length})');scales.push(+l.scale);if(n===150){check(label+' four rows then pages',+l.pages>1&&+l.rows===4,l);await click('[data-action="table-page"][data-page="1"]');await audit(label+' page 2',v.lang);const uid=await ev('+document.querySelector(".card-row .tile").dataset.uid');await click(`.card-row .tile[data-uid="${uid}"]`);check(label+' select on page 2',await ev('!!document.querySelector(".inspect-art")'));await capture(label+'-page2');const before=(await state()).flips;await click('#draw');check(label+' newest card appears on its page',await ev('document.querySelector(".card-row .tile[data-uid=\\"'+(n+1)+'\\"]")!==null'));check(label+' hidden pages retain engine state',(await state()).flips===before+1);}
    if(n===35)await capture(label+'-autoscale');
  }check(label+' cards shrink before paging',scales[1]<=scales[0]&&scales[2]<=scales[1],scales);
  let d=dicePractice();d.practice=false;await seed(d,v.lang);const before=JSON.stringify(await state());await click('#die-hand',false);await wait(80);check(label+' clicking shakes die without spending roll',await ev('document.querySelector("#die-hand canvas").dataset.shaking==="true"'));check(label+' shake leaves random state unchanged',JSON.stringify(await state())===before);await wait(450);
  const hand=await point('#die-hand'),tray=await point('.tray-die-button');await send('Input.dispatchMouseEvent',{type:'mousePressed',...hand,button:'left',clickCount:1});for(let i=1;i<=6;i++){await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:hand.x+(tray.x-hand.x)*i/6,y:hand.y+(tray.y-hand.y)*i/6,button:'left',buttons:1});await wait(24);}check(label+' hand follows drag',await ev('document.querySelector("#die-hand").classList.contains("dragging")'));await send('Input.dispatchMouseEvent',{type:'mouseReleased',...tray,button:'left',clickCount:1});await wait(270);check(label+' drop starts a 20-face throw',await ev('document.querySelector("canvas[data-d20=tray]")?.dataset.rolling==="true"'));await capture(label+'-throw');await idle();let rs=await state();check(label+' one gesture one roll',rs.dice.rolls.length===1);await audit(label+' die result',v.lang);await capture(label+'-die');
  await send('Page.reload',{ignoreCache:true});await wait(130);await idle();await click('[data-action="continue"]');check(label+' die persisted',JSON.stringify((await state()).dice)===JSON.stringify(rs.dice));if(!rs.dice.result.locked){await click('#reroll');check(label+' reroll puts die in hand without spending',await ev('!!document.querySelector("#die-hand")')&&(await state()).dice.rolls.length===1);await click('#roll');check(label+' reroll once',(await state()).dice.rolls.length===2);}await click('#accept-dice');await audit(label+' draft',v.lang);await click('[data-action="add"]');await click('[data-action="remove"]:not(:disabled)');await click('#next');check(label+' round transitions',(await state()).round===2);await audit(label+' next',v.lang);
  await click('[data-action="catalog"]');check(label+' 27 concise cards',await ev('document.querySelectorAll(".catalog-card").length===27'));await audit(label+' catalog',v.lang);await click('[data-action="close"]');await click('[data-action="rules"]');await audit(label+' rules',v.lang);await click('[data-action="close"]');console.log('Verified',label);
 }
 await send('Emulation.setDeviceMetricsOverride',{width:1280,height:800,deviceScaleFactor:1,mobile:false});
 for(const n of [1,20,5,18]){await seed(rollValue(n),'zh');await audit('d20 '+n,'zh');await capture('d20-'+n);if(n===1||n===20){check('natural '+n+' UI locks',await ev('!document.querySelector("#reroll")&&!document.querySelector("#die-hand")&&document.querySelector(".tray-die-button").disabled'));await send('Page.reload',{ignoreCache:true});await wait(130);await idle();await click('[data-action="continue"]');check('natural '+n+' stays locked after reload',await ev('document.querySelector(".tray-die-button").disabled'));}await click('#accept-dice');check('die '+n+' target exact',(await state()).target===3+n);await click('#next');if(n===20)check('feast supplies 12 points',await ev('document.querySelector(".table-score strong").textContent==="12"'));}
 let s=fixture(7);s.cards=s.cards.filter(c=>c.zone==='table'||c.kind==='bomb');s.draw=[s.cards.find(c=>c.kind==='bomb').uid];await seed(s);await click('#draw');check('bomb remains terminal',(await state()).reason==='bomb');
 s=fixture(1);await seed(s);await click('#stop');check('shortfall asks before ending',(await state()).phase==='play');await click('[data-action="choose"][data-index="1"]');check('confirmed shortfall ends',(await state()).reason==='target');
 await seed(fixture(35));await click('[data-action="fullscreen"]');await wait(160);check('fullscreen enters',await ev('!!document.fullscreenElement'));await audit('fullscreen table','zh');await click('[data-action="fullscreen"]');check('fullscreen exits',await ev('!document.fullscreenElement'));
 check('no browser exceptions',t.errors.length===0,t.errors);
}catch(error){report.failures.push(error.message);console.error(error);await capture('failure').catch(()=>{});process.exitCode=1;}finally{report.date=new Date().toISOString();await writeFile(resolve(out,'report.json'),JSON.stringify(report,null,2));console.log({checks:report.checks.length,failures:report.failures,captures:report.captures.length});t.close();}if(report.failures.length)process.exitCode=1;
