import {practiceRun,kitchenPractice,systemPractice} from '../test/fixtures.js';
import {dicePractice} from '../test/fixtures.js';
import {VERSION} from '../game/cards.js';
import {ROUTES} from '../game/routes.js';
import {EXTRA_CARDS} from '../game/extra-cards.js';
import {effectTargets} from '../game/engine.js';
import {TRIALS} from '../test/trials.js';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {connectSmokeTransport} from './smoke-transport.mjs';
import {newRun,act,SAVE_KEY,PREF_KEY,INITIAL_TARGET} from '../game/engine.js';
export async function runBrowserSmoke({transport,root,logger=console,remaining=false,effects=false,skipExtended=false,viewports=null}={}){
const t=transport||await connectSmokeTransport(Number(process.env.EDGE_DEBUG_PORT||9227)),{send}=t,out=resolve(root||process.cwd(),'.artifacts/smoke-one-more-v'+VERSION.replaceAll('.',''));await mkdir(out,{recursive:true});
const report=remaining?{...JSON.parse(await readFile(out+'/report.json','utf8')),failures:[]}:{version:VERSION,checks:[],captures:[],failures:[]},wait=ms=>new Promise(r=>setTimeout(r,ms));
async function ev(expression){const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
async function idle(){for(let n=0;n<100;n++){if(await ev('document.querySelector(".brand")&&document.body.dataset.busy!=="true"&&document.body.dataset.paging!=="true"'))return;await wait(40);}throw Error('UI busy');}
async function point(sel){if(sel==='#next'){const visible=await ev('(()=>{const e=document.querySelector("#next"),r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));})()');check('Next table is visible without auto-scrolling',visible);if(!visible)throw Error('Next table hidden outside viewport');}return ev(`(()=>{const e=[...document.querySelectorAll(${JSON.stringify(sel)})].find(e=>e.getClientRects().length);if(!e||e.disabled)throw Error('Unavailable '+${JSON.stringify(sel)});e.scrollIntoView({block:'nearest',inline:'nearest'});const r=e.getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2;if(!e.contains(document.elementFromPoint(x,y)))throw Error('Covered '+${JSON.stringify(sel)});return {x,y};})()`);}
async function click(sel,settle=true){const p=await point(sel);await send('Input.dispatchMouseEvent',{type:'mousePressed',...p,button:'left',clickCount:1});await send('Input.dispatchMouseEvent',{type:'mouseReleased',...p,button:'left',clickCount:1});if(settle){await wait(35);await idle();}}
function check(label,ok,detail=null){report.checks.push({label,ok:!!ok,detail});if(!ok){report.failures.push(label);console.log('FAIL',label,detail);}}
async function capture(name){await ev('window.scrollTo(0,0)');const r=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(resolve(out,name+'.png'),Buffer.from(r.data,'base64'));report.captures.push(name);}
async function state(){return ev(`JSON.parse(localStorage.getItem(${JSON.stringify(SAVE_KEY)}))`);}
async function seed(s,lang='zh'){s=structuredClone(s);s.practice=false;await ev(`localStorage.setItem('one-more.clean.v060','1');localStorage.setItem('one-more.player.v1',JSON.stringify({tutorialComplete:true,tutorialVersion:3,storySeen:true,storyVersion:3,loops:1}));localStorage.setItem(${JSON.stringify(SAVE_KEY)},${JSON.stringify(JSON.stringify(s))});localStorage.setItem(${JSON.stringify(PREF_KEY)},${JSON.stringify(JSON.stringify({lang,sound:false,motion:true,music:false}))})`);await send('Page.reload',{ignoreCache:true});await wait(130);await idle();await click('[data-action="continue"]');}
function fixture(n=5){const s=newRun(92);s.cards=[];s.table=[];s.draw=[];s.uid=0;s.flips=n;s.bank=0;const kinds=['rice','fish','mint','tea','toast','wild','torch','scope','jar','relay','candle','timetable'];for(let i=0;i<n+3;i++){const kind=i===n+2?'bomb':kinds[i%kinds.length],zone=i<n?'table':'deck';const c={uid:++s.uid,original:kind,kind,zone,tapped:i<n&&['torch','jar'].includes(kind),pair:null,pairedOnce:false,sealedBy:null,ferment:null,caught:null,paid:false,entered:i+1,triggers:0,freeCost:false,multiplier:1};s.cards.push(c);s[zone==='table'?'table':'draw'].push(c.uid);}return s;}
function rollValue(n){for(let seed=0;seed<1000;seed++){const s=dicePractice();s.practice=false;s.rng=seed;const r=act(s,{type:'roll'});if(r.dice.result.total===n)return r;}}
async function choosePath(){const s=await state(),id=s.routeOffers.find(id=>ROUTES[id].type==='event')||s.routeOffers[0];await click(`[data-action="route"][data-id="${id}"]`);if(ROUTES[id].type!=='event')await click('.route-target');}
async function controls(label){const r=await ev('(()=>{const a=document.querySelector("#draw").getBoundingClientRect(),b=document.querySelector("#stop").getBoundingClientRect(),h=document.querySelector(".brand").getBoundingClientRect();return {ratio:a.width*a.height/(b.width*b.height),adjacent:a.left-b.right,visible:a.bottom<=innerHeight&&b.bottom<=innerHeight,center:Math.abs(h.x+h.width/2-document.documentElement.clientWidth/2)}})()');check(label+' One More dominates',r.ratio>1.7,r);check(label+' cash out adjacent and visible',r.adjacent>=0&&r.adjacent<25&&r.visible,r);check(label+' brand centered',r.center<2,r);}
async function audit(label,lang){const a=await ev(`(()=>{const f=document.querySelector('.card-field'),r=f?.getBoundingClientRect(),a=document.querySelector('.table-actions'),tiles=[...document.querySelectorAll('.card-row .tile')],rects=tiles.map(e=>e.getBoundingClientRect());let overlaps=0;for(let i=0;i<rects.length;i++)for(let j=i+1;j<rects.length;j++)if(Math.min(rects[i].right,rects[j].right)-Math.max(rects[i].left,rects[j].left)>2&&Math.min(rects[i].bottom,rects[j].bottom)-Math.max(rects[i].top,rects[j].top)>2)overlaps++;return {page:document.documentElement.scrollWidth<=innerWidth+1,noScroll:!f||f.scrollHeight<=f.clientHeight+1,rows:document.querySelectorAll('.card-row').length,inside:!f||rects.every(x=>(f.dataset.touch==='true'||x.left>=r.left&&x.right<=r.right)&&x.top>=r.top&&x.bottom<=r.bottom),separate:!f||!a||r.bottom<=a.getBoundingClientRect().top+1,overlaps,text:document.body.innerText.replace(document.querySelector('[data-action="language"]')?.innerText||'','')};})()`);
 check(label+' viewport',a.page);check(label+' table has no scrollbar',a.noScroll);check(label+' maximum four rows',a.rows<=4);check(label+' cards stay inside table',a.inside);check(label+' actions do not cover cards',a.separate);check(label+' tilted cards do not overlap',a.overlaps===0,a.overlaps);if(lang==='en')check(label+' English',!/[\u3400-\u9fff]/u.test(a.text),a.text.match(/[\u3400-\u9fff]+/gu));}
try{
 await send('Page.enable');await send('Runtime.enable');await send('Log.enable');t.errors.length=0;
 if(!remaining)for(const v of viewports||[{width:1280,height:800,lang:'zh'},{width:1920,height:1080,lang:'en'},{width:960,height:600,lang:'zh'},{width:390,height:844,lang:'en'}]){
  const label=`${v.width}-${v.height}-${v.lang}`;await send('Emulation.setDeviceMetricsOverride',{width:v.width,height:v.height,deviceScaleFactor:1,mobile:v.width<600});await send('Page.navigate',{url:'http://127.0.0.1:8888/'});await wait(140);await idle();await seed(newRun(29),v.lang);await click('[data-action="home"]');await audit(label+' home',v.lang);check(label+' centered menu title',await ev('(()=>{const r=document.querySelector(".main-menu h1").getBoundingClientRect();return Math.abs(r.x+r.width/2-document.documentElement.clientWidth/2)<2})()'));await capture(label+'-home');
  await click('[data-action="new"]');await audit(label+' new',v.lang);await controls(label);await capture(label+'-new');await seed(practiceRun(),v.lang);await click('.tile[data-uid="3"]');await click('[data-action="use"]');await click('.tile[data-uid="4"]');await click('.tile[data-uid="4"]');await click('[data-action="pair"]');await click('.tile[data-uid="1"]');await click('.tile[data-uid="2"]');await click('.tile[data-uid="2"]');await click('[data-action="use"]');
  check(label+' practice score 4+4',await ev('document.querySelector(".table-score strong").textContent==="8"'));await audit(label+' combo',v.lang);await capture(label+'-combo');await click('#stop');check(label+' practice completes',await ev('!!document.querySelector(".result")'));
  const scales=[];for(const n of [16,35,150]){await seed(fixture(n),v.lang);await audit(label+' '+n+' cards',v.lang);const l=await ev('({...document.querySelector(".card-field").dataset,visible:document.querySelectorAll(".card-row .tile").length})');scales.push(+l.scale);if(n===150&&l.touch==='true'){check(label+' continuous row without pagination',+l.pages===1&&+l.rows===1&&l.visible===150,l);await ev('document.querySelector(".card-field").scrollLeft=700');check(label+' scrolls freely',await ev('document.querySelector(".card-field").scrollLeft>600'));await capture(label+'-continuous-row');}if(n===150&&l.touch!=='true'){check(label+' four rows then pages',+l.pages>1&&+l.rows<=(l.touch==='true'?2:4),l);await click('[data-action="table-page"][data-page="1"]');await audit(label+' page 2',v.lang);const uid=await ev('+document.querySelector(".card-row .tile").dataset.uid');await click(`.card-row .tile[data-uid="${uid}"]`);check(label+' select on page 2',await ev('!!document.querySelector(".inspect-art")'));await capture(label+'-page2');const before=(await state()).flips;await click('#draw');check(label+' newest card appears on its page',await ev('document.querySelector(".card-row .tile[data-uid=\\"'+(n+1)+'\\"]")!==null'));check(label+' hidden pages retain engine state',(await state()).flips===before+1);}
    if(n===35)await capture(label+'-autoscale');
  }check(label+' cards shrink before paging',scales[1]<=scales[0]&&scales[2]<=scales[1],scales);
  let d=dicePractice();d.practice=false;await seed(d,v.lang);const before=JSON.stringify(await state());await ev("window.__sawShake=false;window.__shakeObserver=new MutationObserver(()=>{if(document.querySelector('#die-hand canvas')?.dataset.shaking==='true')window.__sawShake=true});window.__shakeObserver.observe(document.querySelector('#die-hand canvas'),{attributes:true,attributeFilter:['data-shaking']})");await click('#die-hand',false);await wait(80);check(label+' clicking shakes die without spending roll',await ev('window.__shakeObserver.disconnect();window.__sawShake'));check(label+' shake leaves random state unchanged',JSON.stringify(await state())===before);await wait(450);
  const hand=await point('#die-hand'),tray=await point('.tray-die-button');await send('Input.dispatchMouseEvent',{type:'mousePressed',...hand,button:'left',clickCount:1});for(let i=1;i<=6;i++){await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:hand.x+(tray.x-hand.x)*i/6,y:hand.y+(tray.y-hand.y)*i/6,button:'left',buttons:1});await wait(24);}check(label+' hand follows drag',await ev('document.querySelector("#die-hand").classList.contains("dragging")'));await send('Input.dispatchMouseEvent',{type:'mouseReleased',...tray,button:'left',clickCount:1});await wait(270);check(label+' drop starts a 20-face throw',await ev('document.querySelector("canvas[data-d20=tray]")?.dataset.rolling==="true"'));await capture(label+'-throw');await idle();let rs=await state();check(label+' one gesture one roll',rs.dice.rolls.length===1);await audit(label+' die result',v.lang);check(label+' die increases target, not bank',rs.bank===d.bank&&rs.target===d.target);check(label+' explicit next-target label',await ev('document.querySelector(".stakes-purpose").textContent.length>10&&document.querySelector(".dice-result label").textContent.length>3'));await capture(label+'-die');
  await send('Page.reload',{ignoreCache:true});await wait(130);await idle();await click('[data-action="continue"]');check(label+' die persisted',JSON.stringify((await state()).dice)===JSON.stringify(rs.dice));if(!rs.dice.result.locked){await click('#reroll');check(label+' reroll puts die in hand without spending',await ev('!!document.querySelector("#die-hand")')&&(await state()).dice.rolls.length===1);await click('#roll');check(label+' reroll once',(await state()).dice.rolls.length===2);}await click('#accept-dice');await audit(label+' paths',v.lang);check(label+' two path choices',await ev('document.querySelectorAll(".route-card").length===2'));await capture(label+'-paths');await choosePath();await audit(label+' draft',v.lang);check(label+' package required before next',await ev('document.querySelector("#next").disabled'));await click('[data-action="add"]');check(label+' no free removal UI',await ev('!document.querySelector("[data-action=remove]")'));await click('#next');check(label+' round transitions',(await state()).round===2);await audit(label+' next',v.lang);
  const beforeDeck=JSON.stringify(await state());await click('#current-deck');const owned=await ev('[...document.querySelectorAll(".owned-card")].map(e=>({kind:e.dataset.kind,count:+e.dataset.count}))');const expected={};for(const c of (await state()).cards.filter(c=>!c.temporary))expected[c.original]=(expected[c.original]||0)+1;check(label+' current deck matches owned counts',owned.length===Object.keys(expected).length&&owned.every(x=>expected[x.kind]===x.count));check(label+' deck inspection is read only',JSON.stringify(await state())===beforeDeck);await audit(label+' owned deck',v.lang);await capture(label+'-owned-deck');await click('[data-action="close"]');
  if(v.width<=600)await click('[data-action="settings"]');await click('[data-action="catalog"]');check(label+' 80 concise cards',await ev('document.querySelectorAll(".catalog-card").length===80'));await audit(label+' catalog',v.lang);await click('[data-action="close"]');await click('[data-action="settings"]');await click('[data-action="rules"]');await audit(label+' rules',v.lang);await click('[data-action="close"]');await seed(kitchenPractice(),v.lang);await click('.tile[data-uid="6"]');check(label+' new-card practice starts at 15',await ev('document.querySelector(".table-score strong").textContent==="15"'));await audit(label+' new cards',v.lang);await capture(label+'-new-cards');
  await click('[data-action="use"]');await click('.tile[data-uid="4"]');check(label+' consumption fridge compost result 19',await ev('document.querySelector(".table-score strong").textContent==="19"&&document.querySelector(".payment-tickets b").textContent==="1"'));await click('#discard-bin');check(label+' garbage contains consumed fish',await ev('document.querySelectorAll(".discard-pile .catalog-card").length===1&&document.querySelector(".discard-pile .catalog-card").dataset.uid==="4"'));await audit(label+' garbage',v.lang);await capture(label+'-garbage');await click('[data-action="close"]');
  await click('.tile[data-uid="9"]');await click('[data-action="use"]');await click('.tile[data-uid="1"]');check(label+' Mold spends 2 banked and grows Cola set',await ev('document.querySelectorAll(".score-box strong")[1].textContent==="6"&&document.querySelector(".table-score strong").textContent==="23"'));await click('.tile[data-uid="10"]');await click('[data-action="pair"]');await click('.tile[data-uid="11"]');check(label+' Popcorn generates one unpaired food',await ev('document.querySelector(".table-score strong").textContent==="29"&&document.querySelectorAll(".tile").length===14'));await audit(label+' kitchen combo',v.lang);await capture(label+'-kitchen-combo');console.log('Verified',label);
 }
 if(skipExtended)return report;
 await send('Emulation.setDeviceMetricsOverride',{width:1280,height:800,deviceScaleFactor:1,mobile:false});
 let s;
 if(!effects){
 for(const n of [1,20,5,18]){await seed(rollValue(n),'zh');await audit('d20 '+n,'zh');await capture('d20-'+n);if(n===1||n===20){check('natural '+n+' UI locks',await ev('!document.querySelector("#reroll")&&!document.querySelector("#die-hand")&&document.querySelector(".tray-die-button").disabled'));await send('Page.reload',{ignoreCache:true});await wait(130);await idle();await click('[data-action="continue"]');check('natural '+n+' stays locked after reload',await ev('document.querySelector(".tray-die-button").disabled'));}await click('#accept-dice');check('die '+n+' target exact',(await state()).target===INITIAL_TARGET+Math.max(8,n));await choosePath();await click('[data-action=add]');await click('#next');if(n===20)check('feast supplies 12 points',await ev('document.querySelector(".table-score strong").textContent==="12"'));}
 s=fixture(7);s.cards=s.cards.filter(c=>c.zone==='table'||c.kind==='bomb');s.draw=[s.cards.find(c=>c.kind==='bomb').uid];await seed(s);await click('#draw',false);await wait(930);check('bomb fuse appears',await ev('document.querySelector("#performance").dataset.blast==="fuse"'));await capture('bomb-fuse');await wait(480);check('bomb has animated ink burst and debris',await ev('!!document.querySelector(".blast-mark")&&document.querySelectorAll(".blast-shard").length===24'));await capture('bomb-burst');await idle();check('bomb remains terminal',(await state()).reason==='bomb');
 s=fixture(1);await seed(s);await click('#stop');check('shortfall asks before ending',(await state()).phase==='play');await click('[data-action="choose"][data-index="1"]');check('confirmed shortfall ends',(await state()).reason==='target');
 s=fixture(6);['rice','rice','scope','timetable','toast','wild'].forEach((k,i)=>{s.cards[i].kind=k;s.cards[i].original=k;s.cards[i].tapped=false;});await seed(s);
 await click('.tile[data-uid="1"]');await click('[data-action="pair"]');await click('.tile[data-uid="2"]');await click('.tile[data-uid="3"]');await click('[data-action="use"]');check('timetable offers paired food for payment',await ev('document.querySelector(".choice-list").textContent.includes("拆开对子")'));await click('.tile[data-uid="1"]');check('paired payment breaks pair and updates displayed score',await ev('document.querySelector(".table-score strong").textContent==="6"')&&(await state()).cards.find(c=>c.uid===2).pair===null);
 await click('.tile[data-uid="5"]');await click('[data-action="pair"]');await click('.tile[data-uid="6"]');await click('[data-action="choose"][data-index="0"]');check('toast reclaim through UI preserves original pair history',(await state()).cards.find(c=>c.uid===1).zone==='table'&&(await state()).cards.find(c=>c.uid===1).pairedOnce);await capture('timetable-payment-reclaim');
 s=fixture(6);['tea','tea','relay','candle','scope','bell'].forEach((k,i)=>{s.cards[i].kind=k;s.cards[i].original=k;s.cards[i].tapped=false;});await seed(s);await click('.tile[data-uid="1"]');await click('[data-action="pair"]');await click('.tile[data-uid="2"]');check('tea relay candle produce stable rewards',(await state()).freePayments===3&&(await state()).known.length===2);await click('.tile[data-uid="5"]');await click('[data-action="use"]');check('free use is immediate and visible',await ev('document.querySelector(".payment-tickets b").textContent==="2"'));await capture('pair-engine');
 s=fixture(0);s.cards[0].kind=s.cards[0].original='wish';await seed(s);await click('#draw',false);await wait(260);check('wish animates its own reveal, not its token',await ev('document.querySelector(".flying-face strong")?.textContent==="许愿签"'));check('revealing card art and text are visible before landing',await ev('(()=>{const f=document.querySelector(".flying-face");return !!f&&[...f.querySelectorAll("*")].every(e=>getComputedStyle(e).visibility==="visible")})()'));await idle();check('wish token appears without an extra draw',(await state()).flips===1&&(await state()).table.length===2);await capture('wish-token');
 await click('#current-deck');check('temporary sauce is excluded from permanent deck',await ev('[...document.querySelectorAll(".owned-card")].reduce((n,e)=>n+(+e.dataset.count),0)===3&&!document.querySelector(".owned-card[data-kind=wild]")'));await click('[data-action="close"]');
 for(const lang of ['zh','en']){s=fixture(1);s.cards[0].kind=s.cards[0].original='sifter';await seed(s,lang);await click('.tile[data-uid="1"]');await click('[data-action="use"]');check(lang+' sieve peeks unknown top',(await state()).known.includes(2)&&(await state()).draw[0]===2);check(lang+' sieve gives keep or discard',await ev('document.querySelectorAll(".choice-list [data-action=choose]").length===2&&document.querySelector("#draw").disabled'));await audit(lang+' sieve choice',lang);await capture(lang+'-sieve-choice');await send('Page.reload',{ignoreCache:true});await wait(150);await idle();await click('[data-action="continue"]');check(lang+' sieve choice resumes after reload',await ev('document.querySelectorAll(".choice-list [data-action=choose]").length===2'));await click('[data-action="choose"][data-index="1"]');check(lang+' sieve discards exactly one without a draw',(await state()).draw[0]===3&&(await state()).flips===1&&(await state()).pending===null);}
 s=fixture(1);s.cards[0].kind=s.cards[0].original='sifter';s.draw=[s.cards.find(c=>c.kind==='bomb').uid,...s.draw.filter(uid=>s.cards.find(c=>c.uid===uid).kind!=='bomb')];await seed(s);await click('.tile[data-uid="1"]');await click('[data-action="use"]');check('sieve bomb can only be kept',await ev('document.querySelectorAll(".choice-list [data-action=choose]").length===1')&&(await state()).phase==='play');await capture('sieve-bomb');await click('[data-action="choose"][data-index="0"]');const sifted=await state();check('sieve keeps known bomb without exploding',sifted.phase==='play'&&sifted.cards.find(c=>c.uid===sifted.draw[0])?.kind==='bomb');
 s=fixture(1);s.cards=s.cards.filter(c=>c.zone==='table'||c.kind==='bomb');s.draw=[s.cards.find(c=>c.kind==='bomb').uid];await seed(s);await click('#draw',false);await wait(950);await click('[data-action="skip-animation"]');check('skipping fuse cannot undo death',(await state()).reason==='bomb'&&await ev('!!document.querySelector(".result")&&!document.querySelector(".bomb-stage")'));await send('Page.reload',{ignoreCache:true});await wait(150);await idle();check('reload cannot continue a dead run',await ev('!document.querySelector("[data-action=continue]")'));
 await seed(s);await click('[data-action="settings"]');await click('[data-action="motion"]');await click('[data-action="close"]');await click('#draw');check('reduced motion bomb still completes',(await state()).reason==='bomb'&&await ev('!!document.querySelector(".result")'));
 }
 await seed(fixture(35));await click('[data-action="settings"]');await click('[data-action="fullscreen"]');await wait(160);check('fullscreen enters',await ev('!!document.fullscreenElement'));await audit('fullscreen table','zh');await click('[data-action="settings"]');await click('[data-action="fullscreen"]');check('fullscreen exits',await ev('!document.fullscreenElement'));

 for(const lang of ['zh','en']){
  for(const id of ['raw','fried','boiled','prune']){
   s=act(rollValue(7),{type:'acceptDice'});s.round=2;s.bank=25;s.routeOffers=[id,'tea'];await seed(s,lang);await click(`[data-action="route"][data-id="${id}"]`);
   await audit(lang+' '+id+' targets',lang);check(lang+' '+id+' excludes bomb',await ev('![...document.querySelectorAll(".route-target")].some(e=>e.dataset.uid==="20")'));await capture(lang+'-'+id+'-targets');
   const unchanged=JSON.stringify(await state());await click('[data-action="cancel"]');check(lang+' '+id+' cancel leaves state unchanged',JSON.stringify(await state())===unchanged);await click(`[data-action="route"][data-id="${id}"]`);await click('.route-target[data-uid="1"]');
   const after=await state();check(lang+' '+id+' takes one route',after.phase==='draft'&&after.routeHistory.length===1);check(lang+' '+id+' correct permanent result',id==='prune'?after.bank===21&&!after.cards.some(c=>c.uid===1):after.cards.find(c=>c.uid===1).enchantment===id);check(lang+' mandatory next remains disabled',await ev('document.querySelector("#next").disabled'));
   await click('#current-deck');if(id!=='prune')check(lang+' '+id+' appears in owned deck',await ev('!!document.querySelector(".deck-enchantment")'));await click('[data-action="close"]');await click('[data-action=add]');await click('[data-action=chooseRelic]');await click('#next');await audit(lang+' '+id+' next table',lang);
  }
  s=fixture(1);s.cards[0].kind=s.cards[0].original='sorter';await seed(s,lang);await click('.tile[data-uid="1"]');await click('[data-action="use"]');const pending=await state();check(lang+' serving tongs offers three foods',await ev('document.querySelectorAll(".choice-list [data-action=choose]").length===3&&document.querySelector("#draw").disabled'));await audit(lang+' discover',lang);await capture(lang+'-discover');
  await send('Page.reload',{ignoreCache:true});await wait(150);await idle();await click('[data-action="continue"]');check(lang+' discovery choices survive reload',JSON.stringify((await state()).pending)===JSON.stringify(pending.pending));await click('[data-action="choose"][data-index="1"]');const discovered=await state();check(lang+' temporary food added without revealing',discovered.cards.at(-1).temporary&&discovered.cards.at(-1).kind===pending.pending.offers[1]&&discovered.flips===1&&JSON.stringify(discovered.draw)===JSON.stringify(pending.draw));
  s=fixture(6);['rice','rice','scope','bell','torch','fish'].forEach((k,i)=>{s.cards[i].kind=s.cards[i].original=k;s.cards[i].tapped=false;});s.cards[0].enchantment='boiled';s.cards[1].enchantment='fried';s.cards[5].enchantment='raw';await seed(s,lang);check(lang+' three stamps visible',await ev('document.querySelectorAll(".enchant-stamp").length===3'));await click('.tile[data-uid="1"]');await audit(lang+' enchant inspector',lang);await capture(lang+'-enchanted-table');await click('.tile[data-uid="3"]');await click('[data-action="use"]');check(lang+' boiled payment explains retention',await ev('document.querySelector(".choice-list").textContent.includes('+JSON.stringify(lang==='zh'?'水煮':'Boiled')+')'));await click('.tile[data-uid="1"]');check(lang+' boiled stays and shows used', (await state()).cards[0].boiledUsed&&(await state()).cards[0].zone==='table');
 }
 for(const lang of ['zh','en']){
  for(const boon of ['scout','meal','sauce']){
   await seed(rollValue(18),lang);await click(`[data-action="boon"][data-id="${boon}"]`);await click('#accept-dice');
   const before=await state();const id=before.routeOffers.find(id=>ROUTES[id].type==='enchant')||before.routeOffers[0];await click(`[data-action="route"][data-id="${id}"]`);if(ROUTES[id].type!=='event')await click('.route-target');
   await click('[data-action="add"]');await click('#next');const reward=await state();
   check(lang+' '+boon+' restored reward applied',boon==='scout'?reward.known.length===3:boon==='meal'?reward.freePayments===2:reward.cards.filter(c=>c.temporary&&c.kind==='wild').length===1);
   await audit(lang+' '+boon+' restored reward',lang);await capture(lang+'-reward-'+boon);
  }
  s=fixture(4);['rice','scope','bell','oil'].forEach((k,i)=>{s.cards[i].kind=s.cards[i].original=k;s.cards[i].tapped=false;});
  s.cards[3].kind=s.cards[3].original='rice';await seed(s,lang);await click('.tile[data-uid="2"]');await click('[data-action="use"]');
  check(lang+' ordinary cost selector never promises residue',await ev('!(/残渣|Residue/.test(document.querySelector(".choice-list").textContent))'));await click('.tile[data-uid="1"]');
  await click('.tile[data-uid="3"]');await click('[data-action="use"]');await click('.tile[data-uid="4"]');await click('.tile[data-uid="2"]');
  check(lang+' Periscope and Bell create no residue',(await state()).cards.every(c=>c.kind!=='residue'));
  await click('[data-action="log"]');check(lang+' cost logs do not claim residue or use obsolete terms',await ev('!(/残渣|Residue|免付|支付|waiv|spent|paying/i.test(document.querySelector("dialog").textContent))'));await capture(lang+'-cost-log');await click('[data-action="close"]');
  s=fixture(2);['rice','oil'].forEach((k,i)=>{s.cards[i].kind=s.cards[i].original=k;});await seed(s,lang);await click('.tile[data-uid="2"]');await click('[data-action="wipe"]');await click('.tile[data-uid="1"]');check(lang+' wiping oil creates no residue',(await state()).cards.every(c=>c.kind!=='residue'));
 }
 for(const v of [{width:1280,height:800,lang:'zh'},{width:390,height:844,lang:'en'}]){
  const {lang}=v;await send('Emulation.setDeviceMetricsOverride',{width:v.width,height:v.height,deviceScaleFactor:1,mobile:v.width<600});await seed(newRun(50),lang);
  await click('[data-action="catalog"]');check(lang+' collection really has 80 cards',await ev('document.querySelectorAll(".catalog-card").length===80'));
  for(const type of ['food','tool','device','trouble']){await click(`[data-action="catalog-filter"][data-id="${type}"]`);check(lang+' '+type+' collection filter count',await ev('document.querySelectorAll(".catalog-card").length')===Object.values({...EXTRA_CARDS,...(await import('../game/cards.js')).CARDS}).filter(d=>d.type===type).length);}
  await click('[data-action="close"]');const savedBeforeTrials=JSON.stringify(await state());
  for(const id of Object.keys(TRIALS)){await seed(systemPractice(id),lang);await audit(lang+' '+id+' fixture',lang);}
  for(const kind of Object.keys(EXTRA_CARDS).filter(k=>EXTRA_CARDS[k].type==='tool')){
   let f=fixture(6);f.bank=16;[''+kind,'rice','fish','torch','residue','fog'].forEach((k,i)=>{f.cards[i].kind=f.cards[i].original=k;f.cards[i].tapped=false;});
   const def=EXTRA_CARDS[kind];f.cards[1].pairedOnce=true;f.cards[2].temporary=true;
   if(def.target==='pair')f.cards[1].pair=f.cards[2].pair=1;
   if(def.target==='consumed'){f.cards[1].zone='discard';f.cards[1].consumed=true;f.table=f.table.filter(u=>u!==2);f.discard=[2];}
   if(def.target==='discardTool'){f.cards[3].zone='discard';f.table=f.table.filter(u=>u!==4);f.discard=[4];}
   const target=effectTargets(f,f.cards[0])[0]?.uid,action={type:'use',uid:1,...(target?{target}:{})},expected=act(f,action);
   await seed(f,lang);await click('.tile[data-uid="1"]');await click('[data-action="use"]');
   if(def.target){await audit(lang+' '+kind+' choice',lang);await click('[data-action="choose"][data-index="0"]');}
   check(lang+' '+kind+' UI settles exactly like rules',JSON.stringify(await state())===JSON.stringify(expected));await audit(lang+' '+kind+' result',lang);
   if(['grill','steamer','ladle','cleaver'].includes(kind))await capture(lang+'-'+kind+'-result');
  }
  let f=fixture(2);f.cards[0].kind=f.cards[0].original=f.cards[1].kind=f.cards[1].original='shrimp';await seed(f,lang);await click('.tile[data-uid="1"]');await click('[data-action="pair"]');await click('.tile[data-uid="2"]');check(lang+' Shrimp has three temporary-tool choices',(await state()).pending.pool==='tool'&&await ev('document.querySelectorAll(".choice-list [data-action=choose]").length===3'));await audit(lang+' shrimp discover',lang);await capture(lang+'-shrimp-discover');await send('Page.reload',{ignoreCache:true});await wait(160);await idle();await click('[data-action="continue"]');await click('[data-action="choose"][data-index="0"]');check(lang+' Shrimp choice survives reload',!(await state()).pending&&(await state()).cards.at(-1).temporary);
 }
 check('no browser exceptions',t.errors.length===0,t.errors);
}catch(error){report.failures.push(error.message);logger.error(error);await capture('failure').catch(()=>{});}finally{report.date=new Date().toISOString();await writeFile(resolve(out,'report.json'),JSON.stringify(report,null,2));logger.log({checks:report.checks.length,failures:report.failures,captures:report.captures.length});t.close();}
return report;
}
if(typeof process!=='undefined'&&process.argv[1]?.endsWith('browser-smoke.mjs')){const report=await runBrowserSmoke({remaining:process.argv.includes('--remaining'),effects:process.argv.includes('--effects')});if(report.failures.length)process.exitCode=1;}
