import {practiceRun} from '../test/fixtures.js';
import {SAVE_KEY,PREF_KEY} from '../game/engine.js';
import {CARDS} from '../game/cards.js';
import {mkdir,writeFile} from 'node:fs/promises';
export async function runPresentationSmoke({send,root}){
 const out=root+'/.artifacts/smoke-one-more-v0100',checks=[];await mkdir(out,{recursive:true});
 const ev=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
 const wait=ms=>new Promise(r=>setTimeout(r,ms));
 const check=(label,ok)=>{checks.push({label,ok});if(!ok)throw Error(label);};
 const capture=async name=>{const r=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(out+'/'+name+'.png',Buffer.from(r.data,'base64'));};
 const click=async selector=>{const p=await ev(`(()=>{const e=document.querySelector(${JSON.stringify(selector)}),r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);for(const type of ['mousePressed','mouseReleased'])await send('Input.dispatchMouseEvent',{type,button:'left',clickCount:1,...p});};
 const s=practiceRun();s.practice=false;s.maxRounds=10;s.target=8;s.cards[1].tapped=false;
 ['raw','fried','boiled'].forEach((enchantment,i)=>Object.assign(s.cards[i],{kind:['fish','rice','mint'][i],original:['fish','rice','mint'][i],enchantment,tapped:false}));
 Object.assign(s.cards[3],{kind:'torch',original:'torch'});s.cards[4].enchantment='raw';s.cards[4].kind=s.cards[4].original='fish';
 await ev(`localStorage.setItem(${JSON.stringify(SAVE_KEY)},${JSON.stringify(JSON.stringify(s))});localStorage.setItem(${JSON.stringify(PREF_KEY)},JSON.stringify({lang:'zh',sound:false,motion:true,music:false}));localStorage.setItem('one-more.player.v1',JSON.stringify({tutorialComplete:true,tutorialVersion:3,storySeen:true,storyVersion:3}));`);
 await send('Page.reload',{});await wait(120);await click('[data-action=continue]');
 await ev("window.__qaCard=document.querySelector('.tile[data-uid=\"1\"]')");await click('.tile[data-uid="1"]');
 check('selected card retains DOM instance',await ev("window.__qaCard===document.querySelector('.tile[data-uid=\"1\"]')"));
 check('three full-face materials have independent layers',await ev("document.querySelectorAll('.card-row .card-material').length===3&&new Set([...document.querySelectorAll('.card-row .card-material')].map(e=>getComputedStyle(e.querySelector('.material-sheen')).animationName)).size===3"));
 check('no dealer in active game',await ev("!document.querySelector('.game-room .host-portrait')"));
 check('table is centered and over twice as wide as high',await ev("(()=>{const r=document.querySelector('.casino-table').getBoundingClientRect();return Math.abs(r.x+r.width/2-innerWidth/2)<2&&r.width/r.height>2})()"));
 await capture('materials-three');
 await click('#draw');await wait(430);
 check('enchanted flying card includes complete material and visible SVG',await ev("(()=>{const c=document.querySelector('.flying-face');return c?.classList.contains('material-raw')&&c.querySelector('.card-material')&&getComputedStyle(c.querySelector('svg')).visibility==='visible'})()"));await capture('material-flip');
 await wait(1200);check('reveal releases interaction',await ev("document.body.dataset.busy==='false'"));
 await click('.tile[data-uid="4"]');await click('[data-action=use]');await wait(260);check('tool uses a live effect canvas',await ev("!!document.querySelector('.table-effects')"));await capture('flashlight-beam');await wait(850);
 check('tool actually peeks and exhausts',await ev(`(()=>{const s=JSON.parse(localStorage.getItem(${JSON.stringify(SAVE_KEY)}));return s.known.length===1&&s.cards.find(c=>c.uid===4).tapped;})()`));
 check('tool effect canvas cleaned up',await ev("!document.querySelector('.table-effects')"));
 const profiles=await ev("(async()=>Object.keys((await import('./game/tool-effects.js')).TOOL_EFFECTS))()");
 for(const kind of profiles)await ev(`(async()=>{const fx=await import('./game/tool-effects.js');const p=fx.effectPoint(document.querySelector('.tile[data-uid="1"]'));const q=fx.effectPoint(document.querySelector('.tile[data-uid="2"]'));await fx.emitEffect(${JSON.stringify(kind)},p,q);return true;})()`);
 check('all tool effect profiles complete',profiles.length===Object.values(CARDS).filter(c=>c.type==='tool').length);
 await ev("document.documentElement.dataset.motion='reduced'");check('reduced motion does not create animated canvas',await ev("(async()=>{const fx=await import('./game/tool-effects.js');await fx.emitEffect('torch',{x:200,y:200,w:100,h:100});return !document.querySelector('.table-effects')})()"));await ev("delete window.__qaCard;document.documentElement.dataset.motion='full'");
 await writeFile(out+'/presentation-report.json',JSON.stringify({checks},null,2));return checks;
}
